import AppKit
import Combine
import CryptoKit
import Foundation

@MainActor
final class ClipboardStore: ObservableObject {
    private enum DefaultsKey {
        static let historyLimit = "historyLimit"
        static let retentionPolicy = "retentionPolicy"
        static let keepPinnedOnClear = "keepPinnedOnClear"
        static let clearUnpinnedOnQuit = "clearUnpinnedOnQuit"
        static let monitoringEnabled = "monitoringEnabled"
        static let monitoringPausedUntil = "monitoringPausedUntil"
        static let ignoredApplications = "ignoredApplications"
        static let directPasteEnabled = "directPasteEnabled"
    }

    private static let maximumCapturedCharacters = 20_000
    private static let maximumCapturedImageBytes = 10 * 1024 * 1024
    private static let defaultHistoryLimit = 50
    private static let pollInterval: TimeInterval = 0.5
    private static let pruneInterval: TimeInterval = 15 * 60
    private static let ignoredPasteboardTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    @Published private(set) var items: [ClipboardItem]
    @Published private(set) var historyLimit: Int
    @Published var retentionPolicy: ClipboardRetentionPolicy {
        didSet {
            defaults.set(retentionPolicy.rawValue, forKey: DefaultsKey.retentionPolicy)
            pruneHistory()
            persist()
        }
    }
    @Published var keepPinnedOnClear: Bool {
        didSet {
            defaults.set(keepPinnedOnClear, forKey: DefaultsKey.keepPinnedOnClear)
        }
    }
    @Published var clearUnpinnedOnQuit: Bool {
        didSet {
            defaults.set(clearUnpinnedOnQuit, forKey: DefaultsKey.clearUnpinnedOnQuit)
        }
    }
    @Published var directPasteEnabled: Bool {
        didSet {
            defaults.set(directPasteEnabled, forKey: DefaultsKey.directPasteEnabled)
        }
    }
    @Published private(set) var isMonitoringEnabled: Bool {
        didSet {
            defaults.set(isMonitoringEnabled, forKey: DefaultsKey.monitoringEnabled)
            if isMonitoringEnabled {
                lastPasteboardChangeCount = pasteboard.changeCount
                startMonitoring()
            } else {
                stopMonitoring()
            }
        }
    }
    @Published private(set) var monitoringPausedUntil: Date?
    @Published private(set) var ignoredApplications: [ClipboardSourceApplication]
    @Published private(set) var lastCopiedID: ClipboardItem.ID?

    private let pasteboard: NSPasteboard
    private let storage: ClipboardStorage
    private let defaults: UserDefaults
    private let sourceApplicationProvider: () -> ClipboardSourceApplication?
    private var lastPasteboardChangeCount: Int
    private var timer: Timer?
    private var pruneTimer: Timer?
    private var clearCopiedIndicatorTask: Task<Void, Never>?
    private var monitoringResumeTask: Task<Void, Never>?
    private var persistTask: Task<Void, Never>?

    var storageLocation: URL {
        storage.fileURL
    }

    func thumbnailData(for item: ClipboardItem) -> Data? {
        storage.thumbnailData(for: item)
    }

    var historySummaryText: String {
        let unpinnedCount = items.filter { !$0.isPinned }.count
        let pinnedCount = items.count - unpinnedCount

        if pinnedCount > 0 {
            return "\(unpinnedCount)/\(historyLimit) unpinned + \(pinnedCount) pinned"
        }

        return "\(unpinnedCount)/\(historyLimit) unpinned"
    }

    var monitoringStatusText: String {
        if isMonitoringEnabled {
            return "Monitoring clipboard"
        }

        if let monitoringPausedUntil, monitoringPausedUntil > Date() {
            let time = Self.pauseTimeFormatter.string(from: monitoringPausedUntil)
            return "Paused until \(time)"
        }

        return "Paused"
    }

    init(
        pasteboard: NSPasteboard = .general,
        storage: ClipboardStorage = ClipboardStorage(),
        defaults: UserDefaults = .standard,
        sourceApplicationProvider: @escaping () -> ClipboardSourceApplication? = ClipboardSourceApplication.frontmost
    ) {
        self.pasteboard = pasteboard
        self.storage = storage
        self.defaults = defaults
        self.sourceApplicationProvider = sourceApplicationProvider
        self.items = storage.load().sorted { $0.lastCopiedAt > $1.lastCopiedAt }
        self.historyLimit = defaults.object(forKey: DefaultsKey.historyLimit) as? Int
            ?? Self.defaultHistoryLimit
        self.retentionPolicy = defaults.string(forKey: DefaultsKey.retentionPolicy)
            .flatMap(ClipboardRetentionPolicy.init(rawValue:))
            ?? .sevenDays
        self.keepPinnedOnClear = defaults.object(forKey: DefaultsKey.keepPinnedOnClear) as? Bool
            ?? true
        self.clearUnpinnedOnQuit = defaults.object(forKey: DefaultsKey.clearUnpinnedOnQuit) as? Bool
            ?? false
        self.directPasteEnabled = defaults.object(forKey: DefaultsKey.directPasteEnabled) as? Bool
            ?? false
        self.ignoredApplications = Self.loadIgnoredApplications(from: defaults)
        let storedMonitoringEnabled = defaults.object(forKey: DefaultsKey.monitoringEnabled) as? Bool
            ?? true
        let storedPausedUntil = defaults.object(forKey: DefaultsKey.monitoringPausedUntil) as? Date
        if let storedPausedUntil, storedPausedUntil > Date() {
            self.monitoringPausedUntil = storedPausedUntil
            self.isMonitoringEnabled = false
        } else {
            self.monitoringPausedUntil = nil
            self.isMonitoringEnabled = storedMonitoringEnabled
            if storedPausedUntil != nil {
                defaults.removeObject(forKey: DefaultsKey.monitoringPausedUntil)
            }
        }
        self.lastPasteboardChangeCount = pasteboard.changeCount

        let oldItems = items
        pruneHistory()
        if items != oldItems {
            persist()
        }
        if isMonitoringEnabled {
            startMonitoring()
        }
        scheduleMonitoringResumeIfNeeded()
        startPeriodicPruning()
    }

    deinit {
        timer?.invalidate()
        pruneTimer?.invalidate()
        clearCopiedIndicatorTask?.cancel()
        monitoringResumeTask?.cancel()
        persistTask?.cancel()
    }

    func visibleItems(matching query: String, filter: ClipboardContentFilter = .all) -> [ClipboardItem] {
        let filteredItems = items.filter { filter.matches($0) }
        let trimmedQuery = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedQuery.isEmpty else {
            return filteredItems
        }

        return filteredItems.filter { item in
            item.searchableText.localizedCaseInsensitiveContains(trimmedQuery)
        }
    }

    func setHistoryLimit(_ limit: Int) {
        historyLimit = min(max(limit, 10), 200)
        defaults.set(historyLimit, forKey: DefaultsKey.historyLimit)
        pruneHistory()
        persist()
    }

    func setMonitoringEnabled(_ enabled: Bool) {
        clearMonitoringPause()
        isMonitoringEnabled = enabled
    }

    func pauseMonitoring(for duration: ClipboardPauseDuration) {
        let until = duration.resumeDate()
        monitoringPausedUntil = until
        defaults.set(until, forKey: DefaultsKey.monitoringPausedUntil)
        isMonitoringEnabled = false
        scheduleMonitoringResumeIfNeeded()
    }

    func addIgnoredApplication(_ application: ClipboardSourceApplication) {
        if let ownBundleIdentifier = Bundle.main.bundleIdentifier,
           application.bundleIdentifier == ownBundleIdentifier {
            return
        }

        guard !ignoredApplications.contains(where: { $0.bundleIdentifier == application.bundleIdentifier }) else {
            return
        }

        ignoredApplications.append(application)
        ignoredApplications.sort { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
        persistIgnoredApplications()
    }

    func removeIgnoredApplication(_ application: ClipboardSourceApplication) {
        ignoredApplications.removeAll { $0.bundleIdentifier == application.bundleIdentifier }
        persistIgnoredApplications()
    }

    func isApplicationIgnored(_ application: ClipboardSourceApplication?) -> Bool {
        guard let application else {
            return false
        }

        return ignoredApplications.contains { $0.bundleIdentifier == application.bundleIdentifier }
    }

    func exportHistory(to url: URL) throws {
        flushPendingPersist()
        try storage.export(items, to: url)
    }

    func importHistory(from url: URL) throws {
        items = try storage.importItems(from: url)
            .sorted { $0.lastCopiedAt > $1.lastCopiedAt }
        pruneHistory()
        flushPendingPersist()
    }

    func copy(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else {
            return
        }

        var updated = items.remove(at: index)
        updated.lastCopiedAt = Date()
        updated.copyCount += 1
        items.insert(updated, at: 0)

        pasteboard.clearContents()
        writeToPasteboard(updated)
        lastPasteboardChangeCount = pasteboard.changeCount
        lastCopiedID = updated.id

        pruneHistory()
        persist()
        clearCopiedIndicator(after: updated.id)
    }

    func copyAndPaste(_ item: ClipboardItem) {
        copy(item)
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.05) {
            PasteSimulator.simulatePaste()
        }
    }

    func copyWithTransformation(_ item: ClipboardItem, transformation: TextTransformation) {
        let transformedText = transformation.applied(to: item.text)
        guard !transformedText.isEmpty else { return }

        pasteboard.clearContents()
        pasteboard.setString(transformedText, forType: .string)
        lastPasteboardChangeCount = pasteboard.changeCount
        record(transformedText, sourceApplication: item.sourceApplication)

        if let recordedItem = items.first, recordedItem.text == transformedText {
            lastCopiedID = recordedItem.id
            clearCopiedIndicator(after: recordedItem.id)
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard let index = items.firstIndex(where: { $0.id == item.id }) else {
            return
        }

        items[index].isPinned.toggle()
        pruneHistory()
        persist()
    }

    func delete(_ item: ClipboardItem) {
        items.removeAll { $0.id == item.id }
        persist()
        storage.removeUnreferencedImageFiles(keeping: items)
    }

    func clearHistory() {
        if keepPinnedOnClear {
            items.removeAll { !$0.isPinned }
        } else {
            items.removeAll()
        }

        persist()
        storage.removeUnreferencedImageFiles(keeping: items)
    }

    private func startMonitoring() {
        guard isMonitoringEnabled else { return }
        timer?.invalidate()

        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.pollPasteboardForChanges()
            }
        }

        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func startPeriodicPruning() {
        pruneTimer?.invalidate()

        let timer = Timer(timeInterval: Self.pruneInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.pruneHistoryAndPersistIfNeeded()
            }
        }

        RunLoop.main.add(timer, forMode: .common)
        self.pruneTimer = timer
    }

    func pollPasteboardForChanges() {
        let currentChangeCount = pasteboard.changeCount

        guard currentChangeCount != lastPasteboardChangeCount else {
            return
        }

        lastPasteboardChangeCount = currentChangeCount

        guard !shouldIgnoreCurrentPasteboard() else {
            return
        }

        let sourceApplication = sourceApplicationProvider()
        guard !isApplicationIgnored(sourceApplication) else {
            return
        }

        let text = Self.normalizedText(pasteboard.string(forType: .string))

        if let image = Self.imagePayload(from: pasteboard) {
            record(image, associatedText: text, sourceApplication: sourceApplication)
            return
        }

        guard let text else {
            return
        }

        let rtfData = pasteboard.data(forType: .rtf)
        let htmlData = pasteboard.data(forType: .html)
        record(text, rtfData: rtfData, htmlData: htmlData, sourceApplication: sourceApplication)
    }

    private func shouldIgnoreCurrentPasteboard() -> Bool {
        guard let types = pasteboard.types else {
            return false
        }

        return types.contains { Self.ignoredPasteboardTypes.contains($0) }
    }

    nonisolated static func clearUnpinnedHistoryOnQuitIfNeeded(
        storage: ClipboardStorage = ClipboardStorage(),
        defaults: UserDefaults = .standard
    ) {
        guard defaults.bool(forKey: DefaultsKey.clearUnpinnedOnQuit) else {
            return
        }

        let keepPinned = defaults.object(forKey: DefaultsKey.keepPinnedOnClear) as? Bool ?? true
        let itemsToKeep = keepPinned ? storage.load().filter(\.isPinned) : []
        storage.save(itemsToKeep)
    }

    func clearUnpinnedHistoryOnQuitIfNeeded() {
        guard clearUnpinnedOnQuit else {
            flushPendingPersist()
            return
        }

        if keepPinnedOnClear {
            items.removeAll { !$0.isPinned }
        } else {
            items.removeAll()
        }

        flushPendingPersist()
    }

    private func record(
        _ text: String,
        rtfData: Data? = nil,
        htmlData: Data? = nil,
        sourceApplication: ClipboardSourceApplication? = nil
    ) {
        guard text.count <= Self.maximumCapturedCharacters else {
            return
        }

        guard text.rangeOfCharacter(from: .whitespacesAndNewlines.inverted) != nil else {
            return
        }

        if let existingIndex = items.firstIndex(where: { $0.text == text }) {
            var existing = items.remove(at: existingIndex)
            existing.lastCopiedAt = Date()
            existing.copyCount += 1
            existing.sourceApplication = sourceApplication ?? existing.sourceApplication
            existing.rtfData = rtfData
            existing.htmlData = htmlData
            items.insert(existing, at: 0)
        } else {
            items.insert(
                ClipboardItem(text: text, rtfData: rtfData, htmlData: htmlData, sourceApplication: sourceApplication),
                at: 0
            )
        }

        pruneHistory()
        persist()
    }

    private func record(
        _ image: ClipboardImagePayload,
        associatedText: String? = nil,
        sourceApplication: ClipboardSourceApplication? = nil
    ) {
        guard let data = image.data, data.count <= Self.maximumCapturedImageBytes else {
            return
        }

        var storedImage = image
        if storedImage.contentHash == nil {
            storedImage.contentHash = Self.contentHash(for: data)
        }

        if let existingIndex = items.firstIndex(where: { item in
            guard let existingHash = item.image?.contentHash,
                  let newHash = storedImage.contentHash else {
                return false
            }
            return existingHash == newHash
        }) {
            var existing = items.remove(at: existingIndex)
            existing.lastCopiedAt = Date()
            existing.copyCount += 1
            existing.sourceApplication = sourceApplication ?? existing.sourceApplication
            items.insert(existing, at: 0)
        } else {
            items.insert(
                ClipboardItem(
                    text: associatedText ?? "",
                    image: storedImage,
                    sourceApplication: sourceApplication
                ),
                at: 0
            )
        }

        pruneHistory()
        persist()
    }

    private func writeToPasteboard(_ item: ClipboardItem) {
        switch item.contentKind {
        case .text:
            pasteboard.setString(item.text, forType: .string)
            if let rtfData = item.rtfData {
                pasteboard.setData(rtfData, forType: .rtf)
            }
            if let htmlData = item.htmlData {
                pasteboard.setData(htmlData, forType: .html)
            }
        case .image:
            guard let imageData = storage.imageData(for: item) else {
                return
            }

            pasteboard.setData(imageData, forType: .png)

            if let nsImage = NSImage(data: imageData), let tiffData = nsImage.tiffRepresentation {
                pasteboard.setData(tiffData, forType: .tiff)
            }

            if !item.text.isEmpty {
                pasteboard.setString(item.text, forType: .string)
            }
        }
    }

    private static func normalizedText(_ text: String?) -> String? {
        guard let text,
              text.count <= maximumCapturedCharacters,
              text.rangeOfCharacter(from: .whitespacesAndNewlines.inverted) != nil else {
            return nil
        }

        return text
    }

    private static func imagePayload(from pasteboard: NSPasteboard) -> ClipboardImagePayload? {
        if let data = pasteboard.data(forType: .png),
           let image = imagePayload(from: data, preservePNGData: true) {
            return image
        }

        if let data = pasteboard.data(forType: .tiff),
           let image = imagePayload(from: data, preservePNGData: false) {
            return image
        }

        guard let image = NSImage(pasteboard: pasteboard), let tiffData = image.tiffRepresentation else {
            return nil
        }

        return imagePayload(from: tiffData, preservePNGData: false)
    }

    private static func imagePayload(from data: Data, preservePNGData: Bool) -> ClipboardImagePayload? {
        guard let bitmap = NSBitmapImageRep(data: data) else {
            return nil
        }

        let pngData: Data
        if preservePNGData {
            pngData = data
        } else {
            guard let convertedData = bitmap.representation(using: .png, properties: [:]) else {
                return nil
            }
            pngData = convertedData
        }

        guard pngData.count <= maximumCapturedImageBytes else {
            return nil
        }

        return ClipboardImagePayload(
            data: pngData,
            thumbnailData: thumbnailPNGData(from: pngData),
            width: bitmap.pixelsWide,
            height: bitmap.pixelsHigh,
            byteCount: pngData.count,
            contentHash: contentHash(for: pngData)
        )
    }

    private static func thumbnailPNGData(from data: Data) -> Data? {
        guard let image = NSImage(data: data), image.size.width > 0, image.size.height > 0 else {
            return nil
        }

        let maxDimension: CGFloat = 96
        let scale = min(maxDimension / image.size.width, maxDimension / image.size.height, 1)
        let thumbnailSize = NSSize(
            width: max(1, round(image.size.width * scale)),
            height: max(1, round(image.size.height * scale))
        )
        let thumbnailImage = NSImage(size: thumbnailSize, flipped: false) { rect in
            image.draw(
                in: rect,
                from: NSRect(origin: .zero, size: image.size),
                operation: .copy,
                fraction: 1
            )
            return true
        }

        guard let tiffData = thumbnailImage.tiffRepresentation,
              let bitmap = NSBitmapImageRep(data: tiffData) else {
            return nil
        }

        return bitmap.representation(using: .png, properties: [:])
    }

    private static func contentHash(for data: Data) -> String {
        SHA256.hash(data: data)
            .map { String(format: "%02x", $0) }
            .joined()
    }

    private func clearMonitoringPause() {
        monitoringResumeTask?.cancel()
        monitoringResumeTask = nil
        monitoringPausedUntil = nil
        defaults.removeObject(forKey: DefaultsKey.monitoringPausedUntil)
    }

    private func scheduleMonitoringResumeIfNeeded() {
        monitoringResumeTask?.cancel()
        monitoringResumeTask = nil

        guard let monitoringPausedUntil else {
            return
        }

        let delay = monitoringPausedUntil.timeIntervalSinceNow
        guard delay > 0 else {
            clearMonitoringPause()
            isMonitoringEnabled = true
            return
        }

        monitoringResumeTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: UInt64(delay * 1_000_000_000))
            guard !Task.isCancelled else { return }
            guard let self,
                  let pausedUntil = self.monitoringPausedUntil,
                  pausedUntil <= Date() else {
                return
            }

            self.clearMonitoringPause()
            self.isMonitoringEnabled = true
        }
    }

    private func persistIgnoredApplications() {
        guard let data = try? JSONEncoder().encode(ignoredApplications) else {
            return
        }

        defaults.set(data, forKey: DefaultsKey.ignoredApplications)
    }

    private static func loadIgnoredApplications(from defaults: UserDefaults) -> [ClipboardSourceApplication] {
        guard let data = defaults.data(forKey: DefaultsKey.ignoredApplications),
              let applications = try? JSONDecoder().decode([ClipboardSourceApplication].self, from: data) else {
            return []
        }

        return applications.sorted {
            $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending
        }
    }

    private static let pauseTimeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.timeStyle = .short
        formatter.dateStyle = .none
        return formatter
    }()

    private func pruneHistory(now: Date = Date()) {
        removeExpiredUnpinnedItems(now: now)
        trimToLimit()
    }

    private func pruneHistoryAndPersistIfNeeded(now: Date = Date()) {
        let oldItems = items

        pruneHistory(now: now)

        if items != oldItems {
            persist()
        }
    }

    private func removeExpiredUnpinnedItems(now: Date) {
        guard let expirationInterval = retentionPolicy.expirationInterval else {
            return
        }

        let cutoffDate = now.addingTimeInterval(-expirationInterval)
        items.removeAll { item in
            !item.isPinned && item.lastCopiedAt < cutoffDate
        }
    }

    private func trimToLimit() {
        var unpinnedCount = 0
        items.removeAll { item in
            if item.isPinned {
                return false
            }
            unpinnedCount += 1
            return unpinnedCount > historyLimit
        }
    }

    private func persist() {
        persistTask?.cancel()
        let snapshot = items
        let storageRef = storage
        persistTask = Task.detached(priority: .utility) {
            try? await Task.sleep(nanoseconds: 150_000_000)
            guard !Task.isCancelled else { return }
            storageRef.save(snapshot)
        }
    }

    func flushPendingPersist() {
        persistTask?.cancel()
        persistTask = nil
        storage.save(items)
    }

    private func clearCopiedIndicator(after id: ClipboardItem.ID) {
        clearCopiedIndicatorTask?.cancel()
        clearCopiedIndicatorTask = Task { @MainActor [weak self] in
            try? await Task.sleep(nanoseconds: 1_200_000_000)
            guard !Task.isCancelled else { return }
            guard self?.lastCopiedID == id else { return }
            self?.lastCopiedID = nil
        }
    }
}
