import AppKit
import Combine
import Foundation
import UniformTypeIdentifiers

enum ClipboardImportStrategy: Sendable, Equatable {
    case merge
    case replace
}

private final class PersistenceGeneration: @unchecked Sendable {
    private let lock = NSLock()
    private var value: UInt64 = 0

    func advance() -> UInt64 {
        lock.lock()
        defer { lock.unlock() }
        value &+= 1
        return value
    }

    func isCurrent(_ generation: UInt64) -> Bool {
        lock.lock()
        defer { lock.unlock() }
        return value == generation
    }
}

private final class ImportCancellationState: @unchecked Sendable {
    private let lock = NSLock()
    private var cancelled = false

    func cancel() {
        lock.lock()
        cancelled = true
        lock.unlock()
    }

    func checkCancellation() throws {
        lock.lock()
        let isCancelled = cancelled
        lock.unlock()
        if isCancelled {
            throw CancellationError()
        }
    }
}

struct ClipboardStoreClock: Sendable {
    var now: @Sendable () -> Date
    var sleep: @Sendable (UInt64) async throws -> Void

    static let live = ClipboardStoreClock(
        now: { Date() },
        sleep: { try await Task.sleep(nanoseconds: $0) }
    )
}

@MainActor
final class ClipboardStore: ObservableObject {
    private enum DefaultsKey {
        static let historyLimit = "historyLimit"
        static let retentionPolicy = "retentionPolicy"
        static let keepPinnedOnClear = "keepPinnedOnClear"
        static let clearUnpinnedOnQuit = "clearUnpinnedOnQuit"
        static let monitoringEnabled = "monitoringEnabled"
        static let monitoringPausedUntil = "monitoringPausedUntil"
        static let ignoredApplications = "ignoredApplications"
        static let directPasteEnabled = "directPasteEnabled"
    }

    private static let defaultHistoryLimit = 50
    private static let pollInterval: TimeInterval = 0.5
    private static let pruneInterval: TimeInterval = 15 * 60
    private static let maximumPendingImageCaptures = 8
    private static let ignoredPasteboardTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    @Published private(set) var items: [ClipboardItem]
    @Published private(set) var historyLimit: Int
    @Published var retentionPolicy: ClipboardRetentionPolicy {
        didSet {
            defaults.set(retentionPolicy.rawValue, forKey: DefaultsKey.retentionPolicy)
            pruneHistory()
            persist()
        }
    }
    @Published var keepPinnedOnClear: Bool {
        didSet {
            defaults.set(keepPinnedOnClear, forKey: DefaultsKey.keepPinnedOnClear)
        }
    }
    @Published var clearUnpinnedOnQuit: Bool {
        didSet {
            defaults.set(clearUnpinnedOnQuit, forKey: DefaultsKey.clearUnpinnedOnQuit)
        }
    }
    @Published var directPasteEnabled: Bool {
        didSet {
            defaults.set(directPasteEnabled, forKey: DefaultsKey.directPasteEnabled)
        }
    }
    @Published private(set) var isMonitoringEnabled: Bool {
        didSet {
            defaults.set(isMonitoringEnabled, forKey: DefaultsKey.monitoringEnabled)
            if isMonitoringEnabled {
                lastPasteboardChangeCount = pasteboard.changeCount
                startMonitoring()
            } else {
                stopMonitoring()
            }
        }
    }
    @Published private(set) var monitoringPausedUntil: Date?
    @Published private(set) var ignoredApplications: [ClipboardSourceApplication]
    @Published private(set) var lastCopiedID: ClipboardItem.ID?
    @Published private(set) var storageErrorMessage: String?
    @Published private(set) var captureWarning: String?
    @Published private(set) var isTransferBusy = false
    @Published private(set) var transferProgressText: String?
    @Published private var thumbnailCache: [ClipboardItem.ID: Data] = [:]

    private let pasteboard: NSPasteboard
    private let storage: ClipboardStorage
    private let defaults: UserDefaults
    private let sourceApplicationProvider: () -> ClipboardSourceApplication?
    private let usesWorkspaceSourceTracking: Bool
    private var lastPasteboardChangeCount: Int
    private var lastActiveApplication: ClipboardSourceApplication?
    nonisolated(unsafe) private var workspaceActivationObserver: NotificationObserverToken?
    nonisolated(unsafe) private var timer: Timer?
    nonisolated(unsafe) private var pruneTimer: Timer?
    private var clearCopiedIndicatorTask: Task<Void, Never>?
    private var monitoringResumeTask: Task<Void, Never>?
    private var imageCaptureWorker: Task<Void, Never>?
    private var imageCaptureWorkerID: UUID?
    private var pendingImageCaptures: [PendingImageCapture] = []
    private var captureGeneration: UInt64 = 0
    nonisolated(unsafe) private var persistWorkItem: DispatchWorkItem?
    private let persistenceQueue = DispatchQueue(label: "CopyClipLite.persistence", qos: .utility)
    private let persistenceGeneration = PersistenceGeneration()
    private let imageProcessor: any ClipboardImageProcessing
    private let pasteboardWriter: any ClipboardPasteboardWriting
    private let transferService: ClipboardTransferService
    private let clock: ClipboardStoreClock
    private var thumbnailLoadIDs: Set<ClipboardItem.ID> = []
    private var thumbnailRetryAfter: [ClipboardItem.ID: Date] = [:]
    private var thumbnailCacheOrder: [ClipboardItem.ID] = []

    var storageLocation: URL {
        storage.fileURL
    }

    func thumbnailData(for item: ClipboardItem) -> Data? {
        storage.thumbnailData(for: item)
    }

    func cachedThumbnailData(for item: ClipboardItem) -> Data? {
        if let inlineData = item.image?.displayData {
            return inlineData
        }
        if let cachedData = thumbnailCache[item.id] {
            return cachedData
        }
        guard !thumbnailLoadIDs.contains(item.id),
              thumbnailRetryAfter[item.id, default: .distantPast] <= clock.now() else {
            return nil
        }

        thumbnailLoadIDs.insert(item.id)
        let storage = storage
        Task { @MainActor [weak self] in
            let result = await Task.detached(priority: .utility) {
                storage.thumbnailDataRepairingIfNeeded(for: item)
            }.value
            guard let self else { return }
            self.thumbnailLoadIDs.remove(item.id)
            guard let result,
                  let itemIndex = self.items.firstIndex(where: { $0.id == item.id }) else {
                self.thumbnailRetryAfter[item.id] = self.clock.now().addingTimeInterval(5)
                return
            }
            self.thumbnailRetryAfter.removeValue(forKey: item.id)
            if self.items[itemIndex].image?.thumbnailFileName != result.fileName {
                self.items[itemIndex].image?.thumbnailFileName = result.fileName
                self.items[itemIndex].image?.thumbnailData = nil
                self.persist()
            }
            self.thumbnailCache[item.id] = result.data
            self.thumbnailCacheOrder.removeAll { $0 == item.id }
            self.thumbnailCacheOrder.append(item.id)
            while self.thumbnailCacheOrder.count > 100 {
                let evictedID = self.thumbnailCacheOrder.removeFirst()
                self.thumbnailCache.removeValue(forKey: evictedID)
            }
        }
        return nil
    }

    var historySummaryText: String {
        let unpinnedCount = items.filter { !$0.isPinned }.count
        let pinnedCount = items.count - unpinnedCount

        if pinnedCount > 0 {
            return "\(unpinnedCount)/\(historyLimit) unpinned + \(pinnedCount) pinned"
        }

        return "\(unpinnedCount)/\(historyLimit) unpinned"
    }

    var monitoringStatusText: String {
        if isMonitoringEnabled {
            return "Monitoring clipboard"
        }

        if let monitoringPausedUntil, monitoringPausedUntil > clock.now() {
            let time = Self.pauseTimeFormatter.string(from: monitoringPausedUntil)
            return "Paused until \(time)"
        }

        return "Paused"
    }

    init(
        pasteboard: NSPasteboard = .general,
        storage: ClipboardStorage = ClipboardStorage(),
        defaults: UserDefaults = .standard,
        sourceApplicationProvider: (() -> ClipboardSourceApplication?)? = nil,
        imageProcessor: any ClipboardImageProcessing = ClipboardImageProcessingService(),
        pasteboardWriter: (any ClipboardPasteboardWriting)? = nil,
        clock: ClipboardStoreClock = .live
    ) {
        let loadResult = storage.loadResult()
        self.pasteboard = pasteboard
        self.storage = storage
        self.defaults = defaults
        self.imageProcessor = imageProcessor
        self.pasteboardWriter = pasteboardWriter ?? SystemClipboardPasteboardWriter(
            pasteboard: pasteboard
        )
        self.transferService = ClipboardTransferService(storage: storage)
        self.clock = clock
        self.sourceApplicationProvider = sourceApplicationProvider ?? ClipboardSourceApplication.frontmost
        self.usesWorkspaceSourceTracking = sourceApplicationProvider == nil
        self.lastActiveApplication = sourceApplicationProvider == nil
            ? ClipboardSourceApplication.frontmost()
            : nil
        switch loadResult {
        case let .success(loadedItems):
            self.items = loadedItems.sorted { $0.lastCopiedAt > $1.lastCopiedAt }
            self.storageErrorMessage = nil
        case let .failure(error):
            self.items = []
            self.storageErrorMessage = error.localizedDescription
        }
        self.captureWarning = nil
        let storedHistoryLimit = defaults.object(forKey: DefaultsKey.historyLimit) as? Int
            ?? Self.defaultHistoryLimit
        let normalizedHistoryLimit = min(max(storedHistoryLimit, 10), 200)
        self.historyLimit = normalizedHistoryLimit
        if storedHistoryLimit != normalizedHistoryLimit {
            defaults.set(normalizedHistoryLimit, forKey: DefaultsKey.historyLimit)
        }
        self.retentionPolicy = defaults.string(forKey: DefaultsKey.retentionPolicy)
            .flatMap(ClipboardRetentionPolicy.init(rawValue:))
            ?? .sevenDays
        self.keepPinnedOnClear = defaults.object(forKey: DefaultsKey.keepPinnedOnClear) as? Bool
            ?? true
        self.clearUnpinnedOnQuit = defaults.object(forKey: DefaultsKey.clearUnpinnedOnQuit) as? Bool
            ?? false
        self.directPasteEnabled = defaults.object(forKey: DefaultsKey.directPasteEnabled) as? Bool
            ?? false
        self.ignoredApplications = Self.loadIgnoredApplications(from: defaults)
        let storedMonitoringEnabled = defaults.object(forKey: DefaultsKey.monitoringEnabled) as? Bool
            ?? true
        let storedPausedUntil = defaults.object(forKey: DefaultsKey.monitoringPausedUntil) as? Date
        if let storedPausedUntil, storedPausedUntil > clock.now() {
            self.monitoringPausedUntil = storedPausedUntil
            self.isMonitoringEnabled = false
        } else if storedPausedUntil != nil {
            self.monitoringPausedUntil = nil
            self.isMonitoringEnabled = true
            defaults.set(true, forKey: DefaultsKey.monitoringEnabled)
            defaults.removeObject(forKey: DefaultsKey.monitoringPausedUntil)
        } else {
            self.monitoringPausedUntil = nil
            self.isMonitoringEnabled = storedMonitoringEnabled
        }
        self.lastPasteboardChangeCount = pasteboard.changeCount

        let oldItems = items
        pruneHistory()
        if items != oldItems {
            persist()
        }
        if isMonitoringEnabled {
            startMonitoring()
        }
        scheduleMonitoringResumeIfNeeded()
        startPeriodicPruning()
        installWorkspaceSourceTrackingIfNeeded()
    }

    deinit {
        timer?.invalidate()
        pruneTimer?.invalidate()
        clearCopiedIndicatorTask?.cancel()
        monitoringResumeTask?.cancel()
        imageCaptureWorker?.cancel()
        _ = persistenceGeneration.advance()
        if let workspaceActivationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(workspaceActivationObserver.value)
        }
    }

    func visibleItems(matching query: String, filter: ClipboardContentFilter = .all) -> [ClipboardItem] {
        let filteredItems = items.filter { filter.matches($0) }
        let trimmedQuery = query.trimmingCharacters(in: .whitespacesAndNewlines)
        guard !trimmedQuery.isEmpty else {
            return filteredItems
        }

        return filteredItems.filter { item in
            item.searchableText.localizedCaseInsensitiveContains(trimmedQuery)
        }
    }

    func setHistoryLimit(_ limit: Int) {
        guard !isTransferBusy else { return }
        historyLimit = min(max(limit, 10), 200)
        defaults.set(historyLimit, forKey: DefaultsKey.historyLimit)
        pruneHistory()
        persist()
    }

    func setMonitoringEnabled(_ enabled: Bool) {
        clearMonitoringPause()
        if !enabled {
            invalidatePendingImageCaptures()
        }
        isMonitoringEnabled = enabled
    }

    func pauseMonitoring(for duration: ClipboardPauseDuration) {
        let until = duration.resumeDate(from: clock.now())
        monitoringPausedUntil = until
        defaults.set(until, forKey: DefaultsKey.monitoringPausedUntil)
        invalidatePendingImageCaptures()
        isMonitoringEnabled = false
        scheduleMonitoringResumeIfNeeded()
    }

    func addIgnoredApplication(_ application: ClipboardSourceApplication) {
        if let ownBundleIdentifier = Bundle.main.bundleIdentifier,
           application.bundleIdentifier == ownBundleIdentifier {
            return
        }

        guard !ignoredApplications.contains(where: { $0.bundleIdentifier == application.bundleIdentifier }) else {
            return
        }

        ignoredApplications.append(application)
        ignoredApplications.sort { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
        persistIgnoredApplications()
    }

    func removeIgnoredApplication(_ application: ClipboardSourceApplication) {
        ignoredApplications.removeAll { $0.bundleIdentifier == application.bundleIdentifier }
        persistIgnoredApplications()
    }

    func isApplicationIgnored(_ application: ClipboardSourceApplication?) -> Bool {
        guard let application else {
            return false
        }

        return ignoredApplications.contains { $0.bundleIdentifier == application.bundleIdentifier }
    }

    func exportHistory(to url: URL) throws {
        flushPendingPersist()
        try storage.export(items, to: url)
    }

    func exportHistoryAsync(to url: URL) async throws {
        guard !isTransferBusy else {
            throw ClipboardStorageError.persistenceFailed
        }
        isTransferBusy = true
        transferProgressText = "Preparing export…"
        defer {
            isTransferBusy = false
            transferProgressText = nil
        }
        let snapshot = items
        try await transferService.export(snapshot, to: url)
    }

    func importPreview(from url: URL) throws -> ClipboardImportPreview {
        try storage.importPreview(from: url)
    }

    func prepareImport(from url: URL) async throws -> ClipboardImportArtifact {
        guard !isTransferBusy else {
            throw ClipboardStorageError.persistenceFailed
        }
        isTransferBusy = true
        transferProgressText = "Validating import…"
        defer {
            isTransferBusy = false
            transferProgressText = nil
        }
        return try await transferService.prepareImport(from: url)
    }

    func prepareImport(
        data: Data,
        sourceFileName: String
    ) async throws -> ClipboardImportArtifact {
        guard !isTransferBusy else {
            throw ClipboardStorageError.persistenceFailed
        }
        isTransferBusy = true
        transferProgressText = "Validating dropped import…"
        defer {
            isTransferBusy = false
            transferProgressText = nil
        }
        return try await transferService.prepareImport(
            data: data,
            sourceFileName: sourceFileName
        )
    }

    func dragItemProvider(for item: ClipboardItem) -> NSItemProvider {
        switch item.contentKind {
        case .text:
            let provider = NSItemProvider(object: item.text as NSString)
            provider.suggestedName = "CopyClip Text"
            if let rtfData = item.rtfData {
                provider.registerDataRepresentation(
                    forTypeIdentifier: UTType.rtf.identifier,
                    visibility: .all
                ) { completion in
                    completion(rtfData, nil)
                    return nil
                }
            }
            if let htmlData = item.htmlData {
                provider.registerDataRepresentation(
                    forTypeIdentifier: UTType.html.identifier,
                    visibility: .all
                ) { completion in
                    completion(htmlData, nil)
                    return nil
                }
            }
            return provider
        case .image:
            let provider = NSItemProvider()
            provider.suggestedName = "CopyClip Image.png"
            let storage = storage
            provider.registerDataRepresentation(
                forTypeIdentifier: UTType.png.identifier,
                visibility: .all
            ) { completion in
                let data = storage.imageData(for: item)
                completion(data, data == nil ? ClipboardStorageError.missingImageData : nil)
                return nil
            }
            provider.registerFileRepresentation(
                forTypeIdentifier: UTType.png.identifier,
                fileOptions: [],
                visibility: .all
            ) { completion in
                guard let data = storage.imageData(for: item) else {
                    completion(nil, false, ClipboardStorageError.missingImageData)
                    return nil
                }
                do {
                    let directory = FileManager.default.temporaryDirectory
                        .appendingPathComponent("CopyClipLite-Drag", isDirectory: true)
                    try FileManager.default.createDirectory(
                        at: directory,
                        withIntermediateDirectories: true
                    )
                    let url = directory.appendingPathComponent(
                        "\(item.id.uuidString)-CopyClip-Image.png"
                    )
                    try data.write(to: url, options: [.atomic])
                    completion(url, false, nil)
                } catch {
                    completion(nil, false, error)
                }
                return nil
            }
            return provider
        }
    }

    func importProjection(
        for artifact: ClipboardImportArtifact,
        strategy: ClipboardImportStrategy,
        now: Date? = nil
    ) -> ClipboardImportProjection {
        importPlan(for: artifact, now: now).projection(for: strategy)
    }

    func importPlan(
        for artifact: ClipboardImportArtifact,
        now: Date? = nil
    ) -> ClipboardImportPlan {
        let now = now ?? clock.now()
        let currentItems = items
        let mergeBeforePruning = mergedItems(
            existing: currentItems,
            imported: artifact.items
        )
        let replaceBeforePruning = artifact.items.sorted {
            $0.lastCopiedAt > $1.lastCopiedAt
        }
        let merge = importCandidate(
            beforePruning: mergeBeforePruning,
            sourceItemCount: artifact.items.count,
            addedCount: max(mergeBeforePruning.count - currentItems.count, 0),
            strategy: .merge,
            now: now
        )
        let replace = importCandidate(
            beforePruning: replaceBeforePruning,
            sourceItemCount: artifact.items.count,
            addedCount: artifact.items.count,
            strategy: .replace,
            now: now
        )
        return ClipboardImportPlan(
            artifact: artifact,
            currentItems: currentItems,
            historyLimit: historyLimit,
            retentionPolicy: retentionPolicy,
            mergeItems: merge.items,
            mergeProjection: merge.projection,
            replaceItems: replace.items,
            replaceProjection: replace.projection
        )
    }

    @discardableResult
    func importHistory(
        artifact: ClipboardImportArtifact,
        strategy: ClipboardImportStrategy
    ) async throws -> ClipboardImportCommit {
        try await importHistory(
            plan: importPlan(for: artifact),
            strategy: strategy
        )
    }

    @discardableResult
    func importHistory(
        plan: ClipboardImportPlan,
        strategy: ClipboardImportStrategy
    ) async throws -> ClipboardImportCommit {
        guard !isTransferBusy else {
            throw ClipboardStorageError.persistenceFailed
        }
        guard items == plan.currentItems,
              historyLimit == plan.historyLimit,
              retentionPolicy == plan.retentionPolicy else {
            throw ClipboardStorageError.importPlanExpired
        }

        isTransferBusy = true
        transferProgressText = "Applying import…"
        invalidatePendingImageCaptures()
        invalidatePendingPersist()
        stopMonitoring()
        defer {
            isTransferBusy = false
            transferProgressText = nil
            if isMonitoringEnabled {
                startMonitoring()
            }
        }

        let commit = try await commitImportOnPersistenceQueue(
            currentItems: plan.currentItems,
            candidateItems: plan.candidateItems(for: strategy)
        )
        items = commit.items
        storageErrorMessage = nil
        return commit
    }

    @discardableResult
    func importHistory(from url: URL, strategy: ClipboardImportStrategy) throws -> URL {
        let importedItems = try storage.importItems(from: url)
        var candidateItems: [ClipboardItem]

        switch strategy {
        case .merge:
            candidateItems = mergedItems(existing: items, imported: importedItems)
        case .replace:
            invalidatePendingImageCaptures()
            candidateItems = importedItems
        }

        candidateItems = prunedItems(candidateItems)
        invalidatePendingPersist()
        let currentItems = items
        let transactionResult = try persistenceQueue.sync {
            try storage.saveValidated(currentItems)
            let backupURL = try storage.backup(currentItems, reason: "pre-import")
            try storage.saveValidated(candidateItems)
            let loadedItems = try storage.loadResult().get().sorted { $0.lastCopiedAt > $1.lastCopiedAt }
            return (backupURL, loadedItems)
        }
        items = transactionResult.1
        storageErrorMessage = nil
        return transactionResult.0
    }

    @discardableResult
    func copy(_ item: ClipboardItem) -> Bool {
        guard !isTransferBusy else {
            return false
        }
        guard let index = items.firstIndex(where: { $0.id == item.id }) else {
            return false
        }

        let imageData: Data?
        if item.contentKind == .image {
            guard let storedImageData = storage.imageData(for: item) else {
                storageErrorMessage = "This image is missing from local storage and was not copied."
                return false
            }
            imageData = storedImageData
        } else {
            imageData = nil
        }

        let writeResult = writeToPasteboard(item, imageData: imageData)
        guard writeResult.wroteRequiredRepresentations else {
            storageErrorMessage = "The clip could not be written to the system clipboard."
            return false
        }
        if case let .degraded(optionalTypes) = writeResult {
            captureWarning = "The clip was copied without optional formats: \(optionalTypes.joined(separator: ", "))."
        }
        storageErrorMessage = nil

        var updated = items.remove(at: index)
        updated.lastCopiedAt = clock.now()
        updated.copyCount += 1
        items.insert(updated, at: 0)

        lastPasteboardChangeCount = pasteboard.changeCount
        lastCopiedID = updated.id

        pruneHistory()
        persist()
        clearCopiedIndicator(after: updated.id)
        return true
    }

    func copyWithTransformation(_ item: ClipboardItem, transformation: TextTransformation) {
        guard !isTransferBusy else { return }
        let transformedText = transformation.applied(to: item.text)
        guard !transformedText.isEmpty else {
            return
        }

        let result = pasteboardWriter.write(
            ClipboardPasteboardWriteRequest(
                required: [
                    ClipboardPasteboardRepresentation(.string, value: .string(transformedText))
                ],
                optional: []
            )
        )
        guard result.wroteRequiredRepresentations else {
            storageErrorMessage = "The transformed clip could not be written to the system clipboard."
            return
        }
        storageErrorMessage = nil
        lastPasteboardChangeCount = pasteboard.changeCount

        if let existingIndex = items.firstIndex(where: {
            $0.contentKind == .text && $0.text == transformedText
        }) {
            var existing = items.remove(at: existingIndex)
            existing.lastCopiedAt = clock.now()
            existing.copyCount += 1
            existing.sourceApplication = item.sourceApplication ?? existing.sourceApplication
            items.insert(existing, at: 0)
        } else {
            items.insert(
                ClipboardItem(text: transformedText, sourceApplication: item.sourceApplication),
                at: 0
            )
        }

        pruneHistory()
        persist()

        if let recordedItem = items.first, recordedItem.text == transformedText {
            lastCopiedID = recordedItem.id
            clearCopiedIndicator(after: recordedItem.id)
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard !isTransferBusy else { return }
        guard let index = items.firstIndex(where: { $0.id == item.id }) else {
            return
        }

        items[index].isPinned.toggle()
        pruneHistory()
        persist()
    }

    func delete(_ item: ClipboardItem) {
        guard !isTransferBusy else { return }
        items.removeAll { $0.id == item.id }
        flushPendingPersist()
    }

    func clearHistory() {
        guard !isTransferBusy else { return }
        invalidatePendingImageCaptures()
        if keepPinnedOnClear {
            items.removeAll { !$0.isPinned }
        } else {
            items.removeAll()
        }

        flushPendingPersist()
    }

    private func startMonitoring() {
        guard isMonitoringEnabled else { return }
        timer?.invalidate()

        let timer = Timer(timeInterval: Self.pollInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.pollPasteboardForChanges()
            }
        }

        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    private func stopMonitoring() {
        timer?.invalidate()
        timer = nil
    }

    private func startPeriodicPruning() {
        pruneTimer?.invalidate()

        let timer = Timer(timeInterval: Self.pruneInterval, repeats: true) { [weak self] _ in
            Task { @MainActor [weak self] in
                self?.pruneHistoryAndPersistIfNeeded()
            }
        }

        RunLoop.main.add(timer, forMode: .common)
        self.pruneTimer = timer
    }

    func pollPasteboardForChanges(sourceApplicationOverride: ClipboardSourceApplication? = nil) {
        guard !isTransferBusy else {
            return
        }
        let currentChangeCount = pasteboard.changeCount

        guard currentChangeCount != lastPasteboardChangeCount else {
            return
        }

        lastPasteboardChangeCount = currentChangeCount

        guard !shouldIgnoreCurrentPasteboard() else {
            return
        }

        let sourceApplication = sourceApplicationOverride
            ?? (usesWorkspaceSourceTracking ? lastActiveApplication : sourceApplicationProvider())
        guard !isApplicationIgnored(sourceApplication) else {
            return
        }

        let capturedText = Self.capturedText(from: pasteboard)
        if let warning = capturedText.warning {
            captureWarning = warning
        }

        if let candidate = Self.imageCandidate(from: pasteboard) {
            let capturedAt = clock.now()
            processImageCandidate(
                candidate,
                associatedText: capturedText.snapshot,
                associatedWarning: capturedText.warning,
                sourceApplication: sourceApplication,
                capturedAt: capturedAt
            )
            return
        }

        guard let textSnapshot = capturedText.snapshot else {
            return
        }

        record(
            textSnapshot.text,
            rtfData: textSnapshot.rtfData,
            htmlData: textSnapshot.htmlData,
            sourceApplication: sourceApplication,
            capturedAt: clock.now()
        )
        captureWarning = capturedText.warning
    }

    private func shouldIgnoreCurrentPasteboard() -> Bool {
        guard let types = pasteboard.types else {
            return false
        }

        return types.contains { Self.ignoredPasteboardTypes.contains($0) }
    }

    private func processImageCandidate(
        _ candidate: ClipboardImageCandidate,
        associatedText: CapturedTextSnapshot?,
        associatedWarning: String?,
        sourceApplication: ClipboardSourceApplication?,
        capturedAt: Date
    ) {
        let queuedCapacity = Self.maximumPendingImageCaptures
            - (imageCaptureWorker == nil ? 0 : 1)
        while pendingImageCaptures.count >= max(queuedCapacity, 0),
              !pendingImageCaptures.isEmpty {
            pendingImageCaptures.removeFirst()
        }

        pendingImageCaptures.append(
            PendingImageCapture(
                candidate: candidate,
                associatedText: associatedText,
                associatedWarning: associatedWarning,
                sourceApplication: sourceApplication,
                capturedAt: capturedAt,
                generation: captureGeneration
            )
        )
        startImageCaptureWorkerIfNeeded()
    }

    private func startImageCaptureWorkerIfNeeded() {
        guard imageCaptureWorker == nil, !pendingImageCaptures.isEmpty else {
            return
        }
        let workerID = UUID()
        imageCaptureWorkerID = workerID
        imageCaptureWorker = Task { @MainActor [weak self] in
            await self?.drainImageCaptureQueue(workerID: workerID)
        }
    }

    private func drainImageCaptureQueue(workerID: UUID) async {
        defer {
            if imageCaptureWorkerID == workerID {
                imageCaptureWorker = nil
                imageCaptureWorkerID = nil
                startImageCaptureWorkerIfNeeded()
            }
        }

        while !Task.isCancelled, !pendingImageCaptures.isEmpty {
            let request = pendingImageCaptures.removeFirst()
            do {
                let image = try await imageProcessor.process(request.candidate)
                guard !Task.isCancelled,
                      captureGeneration == request.generation else {
                    continue
                }
                record(
                    image,
                    associatedText: request.associatedText?.text,
                    sourceApplication: request.sourceApplication,
                    capturedAt: request.capturedAt
                )
                captureWarning = request.associatedWarning
            } catch is CancellationError {
                return
            } catch {
                guard !Task.isCancelled,
                      captureGeneration == request.generation else {
                    continue
                }
                captureWarning = error.localizedDescription
                if let associatedText = request.associatedText {
                    record(
                        associatedText.text,
                        rtfData: associatedText.rtfData,
                        htmlData: associatedText.htmlData,
                        sourceApplication: request.sourceApplication,
                        capturedAt: request.capturedAt
                    )
                }
            }
        }
    }

    private func invalidatePendingImageCaptures() {
        captureGeneration &+= 1
        pendingImageCaptures.removeAll()
        imageCaptureWorker?.cancel()
        imageCaptureWorker = nil
        imageCaptureWorkerID = nil
    }

    nonisolated static func clearUnpinnedHistoryOnQuitIfNeeded(
        storage: ClipboardStorage = ClipboardStorage(),
        defaults: UserDefaults = .standard
    ) {
        guard defaults.bool(forKey: DefaultsKey.clearUnpinnedOnQuit) else {
            return
        }

        let itemsToKeep = itemsAfterQuitCleanup(storage.load())
        _ = try? storage.saveValidated(itemsToKeep)
    }

    func clearUnpinnedHistoryOnQuitIfNeeded() {
        invalidatePendingImageCaptures()
        guard clearUnpinnedOnQuit else {
            flushPendingPersist()
            return
        }

        items = Self.itemsAfterQuitCleanup(items)

        flushPendingPersist()
    }

    nonisolated private static func itemsAfterQuitCleanup(
        _ items: [ClipboardItem]
    ) -> [ClipboardItem] {
        items.filter(\.isPinned)
    }

    private func record(
        _ text: String,
        rtfData: Data? = nil,
        htmlData: Data? = nil,
        sourceApplication: ClipboardSourceApplication? = nil,
        capturedAt: Date? = nil
    ) {
        let capturedAt = capturedAt ?? clock.now()
        guard text.count <= ClipboardStorage.maximumImportedTextCharacters else {
            captureWarning = "A text clip was skipped because it exceeds 20,000 characters."
            return
        }

        guard text.rangeOfCharacter(from: .whitespacesAndNewlines.inverted) != nil else {
            return
        }

        if let existingIndex = items.firstIndex(where: {
            $0.contentKind == .text && $0.text == text
        }) {
            var existing = items.remove(at: existingIndex)
            let isNewestRepresentation = capturedAt >= existing.lastCopiedAt
            existing.lastCopiedAt = max(existing.lastCopiedAt, capturedAt)
            existing.copyCount += 1
            if isNewestRepresentation {
                existing.sourceApplication = sourceApplication ?? existing.sourceApplication
                existing.rtfData = rtfData
                existing.htmlData = htmlData
            }
            items.insert(existing, at: 0)
        } else {
            items.insert(
                ClipboardItem(text: text, rtfData: rtfData, htmlData: htmlData, sourceApplication: sourceApplication),
                at: 0
            )
        }

        pruneHistory()
        persist()
    }

    private func record(
        _ image: ClipboardImagePayload,
        associatedText: String? = nil,
        sourceApplication: ClipboardSourceApplication? = nil,
        capturedAt: Date? = nil
    ) {
        let capturedAt = capturedAt ?? clock.now()
        guard let data = image.data, data.count <= ClipboardImageProcessor.maximumEncodedBytes else {
            captureWarning = ClipboardImageProcessingError.encodedDataTooLarge.localizedDescription
            return
        }

        var storedImage = image
        if storedImage.contentHash == nil {
            storedImage.contentHash = ClipboardImageProcessor.contentHash(for: data)
        }

        if let existingIndex = items.firstIndex(where: { item in
            guard let existingHash = item.image?.contentHash,
                  let newHash = storedImage.contentHash else {
                return false
            }
            return existingHash == newHash
        }) {
            var existing = items.remove(at: existingIndex)
            let isNewestRepresentation = capturedAt >= existing.lastCopiedAt
            existing.lastCopiedAt = max(existing.lastCopiedAt, capturedAt)
            existing.copyCount += 1
            if isNewestRepresentation {
                existing.sourceApplication = sourceApplication ?? existing.sourceApplication
                existing.text = associatedText ?? ""
                existing.image = storedImage
            }
            items.insert(existing, at: 0)
        } else {
            items.insert(
                ClipboardItem(
                    text: associatedText ?? "",
                    image: storedImage,
                    createdAt: capturedAt,
                    lastCopiedAt: capturedAt,
                    sourceApplication: sourceApplication
                ),
                at: 0
            )
        }

        items.sort { $0.lastCopiedAt > $1.lastCopiedAt }
        pruneHistory()
        persist()
    }

    @discardableResult
    private func writeToPasteboard(
        _ item: ClipboardItem,
        imageData: Data?
    ) -> ClipboardPasteboardWriteResult {
        let request: ClipboardPasteboardWriteRequest
        switch item.contentKind {
        case .text:
            var optional: [ClipboardPasteboardRepresentation] = []
            if let rtfData = item.rtfData {
                optional.append(ClipboardPasteboardRepresentation(.rtf, value: .data(rtfData)))
            }
            if let htmlData = item.htmlData {
                optional.append(ClipboardPasteboardRepresentation(.html, value: .data(htmlData)))
            }
            request = ClipboardPasteboardWriteRequest(
                required: [
                    ClipboardPasteboardRepresentation(.string, value: .string(item.text))
                ],
                optional: optional
            )
        case .image:
            guard let imageData else {
                return .failure
            }
            var optional: [ClipboardPasteboardRepresentation] = []
            if !item.text.isEmpty {
                optional.append(
                    ClipboardPasteboardRepresentation(.string, value: .string(item.text))
                )
            }
            request = ClipboardPasteboardWriteRequest(
                required: [
                    ClipboardPasteboardRepresentation(.png, value: .data(imageData))
                ],
                optional: optional
            )
        }
        return pasteboardWriter.write(request)
    }

    private struct CapturedTextSnapshot {
        let text: String
        let rtfData: Data?
        let htmlData: Data?
    }

    private struct PendingImageCapture {
        let candidate: ClipboardImageCandidate
        let associatedText: CapturedTextSnapshot?
        let associatedWarning: String?
        let sourceApplication: ClipboardSourceApplication?
        let capturedAt: Date
        let generation: UInt64
    }

    private struct CapturedTextResult {
        let snapshot: CapturedTextSnapshot?
        let warning: String?
    }

    private static func capturedText(from pasteboard: NSPasteboard) -> CapturedTextResult {
        let rawRTFData = pasteboard.data(forType: .rtf)
        let rawHTMLData = pasteboard.data(forType: .html)
        let text = pasteboard.string(forType: .string)
            ?? attributedPlainText(data: rawRTFData, documentType: .rtf)
            ?? attributedPlainText(data: rawHTMLData, documentType: .html)

        guard let text else {
            return CapturedTextResult(snapshot: nil, warning: nil)
        }
        guard text.rangeOfCharacter(from: .whitespacesAndNewlines.inverted) != nil else {
            return CapturedTextResult(snapshot: nil, warning: nil)
        }
        guard text.count <= ClipboardStorage.maximumImportedTextCharacters else {
            return CapturedTextResult(
                snapshot: nil,
                warning: "A text clip was skipped because it exceeds 20,000 characters."
            )
        }

        let rtfData = rawRTFData.flatMap {
            $0.count <= ClipboardStorage.maximumImportedRichTextBytes ? $0 : nil
        }
        let htmlData = rawHTMLData.flatMap {
            $0.count <= ClipboardStorage.maximumImportedRichTextBytes ? $0 : nil
        }
        let droppedFormats = [
            rawRTFData != nil && rtfData == nil ? "RTF" : nil,
            rawHTMLData != nil && htmlData == nil ? "HTML" : nil
        ].compactMap { $0 }
        let warning = droppedFormats.isEmpty
            ? nil
            : "The text was saved without oversized \(droppedFormats.joined(separator: " and ")) formatting."
        return CapturedTextResult(
            snapshot: CapturedTextSnapshot(text: text, rtfData: rtfData, htmlData: htmlData),
            warning: warning
        )
    }

    private static func attributedPlainText(
        data: Data?,
        documentType: NSAttributedString.DocumentType
    ) -> String? {
        guard let data else { return nil }
        return try? NSAttributedString(
            data: data,
            options: [.documentType: documentType],
            documentAttributes: nil
        ).string
    }

    private static func imageCandidate(from pasteboard: NSPasteboard) -> ClipboardImageCandidate? {
        if let data = pasteboard.data(forType: .png) {
            return ClipboardImageCandidate(data: data, isPNG: true)
        }

        if let data = pasteboard.data(forType: .tiff) {
            return ClipboardImageCandidate(data: data, isPNG: false)
        }

        for type in [
            NSPasteboard.PasteboardType("public.jpeg"),
            NSPasteboard.PasteboardType("public.heic"),
            NSPasteboard.PasteboardType("public.heif")
        ] {
            if let data = pasteboard.data(forType: type) {
                return ClipboardImageCandidate(data: data, isPNG: false)
            }
        }

        if let fileURLString = pasteboard.string(forType: .fileURL),
           let fileURL = URL(string: fileURLString),
           fileURL.isFileURL,
           let resourceValues = try? fileURL.resourceValues(forKeys: [.fileSizeKey, .isRegularFileKey]),
           resourceValues.isRegularFile == true,
           resourceValues.fileSize ?? 0 <= ClipboardImageProcessor.maximumInputBytes,
           let data = try? Data(contentsOf: fileURL, options: [.mappedIfSafe]),
           ClipboardImageProcessor.isDecodableImage(data) {
            return ClipboardImageCandidate(data: data, isPNG: false)
        }

        return nil
    }

    private func installWorkspaceSourceTrackingIfNeeded() {
        guard usesWorkspaceSourceTracking else { return }
        workspaceActivationObserver = NotificationObserverToken(
            NSWorkspace.shared.notificationCenter.addObserver(
                forName: NSWorkspace.didActivateApplicationNotification,
                object: nil,
                queue: .main
            ) { [weak self] notification in
                guard let runningApplication = notification.userInfo?[NSWorkspace.applicationUserInfoKey]
                        as? NSRunningApplication else { return }
                MainActor.assumeIsolated {
                    guard let self else { return }
                    let previousApplication = self.lastActiveApplication
                    self.pollPasteboardForChanges(sourceApplicationOverride: previousApplication)
                    self.lastActiveApplication = ClipboardSourceApplication(
                        runningApplication: runningApplication
                    )
                }
            }
        )
    }

    private func clearMonitoringPause() {
        monitoringResumeTask?.cancel()
        monitoringResumeTask = nil
        monitoringPausedUntil = nil
        defaults.removeObject(forKey: DefaultsKey.monitoringPausedUntil)
    }

    private func scheduleMonitoringResumeIfNeeded() {
        monitoringResumeTask?.cancel()
        monitoringResumeTask = nil

        guard let monitoringPausedUntil else {
            return
        }

        let delay = monitoringPausedUntil.timeIntervalSince(clock.now())
        guard delay > 0 else {
            clearMonitoringPause()
            isMonitoringEnabled = true
            return
        }

        monitoringResumeTask = Task { @MainActor [weak self] in
            guard let self else { return }
            try? await self.clock.sleep(UInt64(delay * 1_000_000_000))
            guard !Task.isCancelled else { return }
            guard let pausedUntil = self.monitoringPausedUntil,
                  pausedUntil <= self.clock.now() else {
                return
            }

            self.clearMonitoringPause()
            self.isMonitoringEnabled = true
        }
    }

    private func persistIgnoredApplications() {
        guard let data = try? JSONEncoder().encode(ignoredApplications) else {
            return
        }

        defaults.set(data, forKey: DefaultsKey.ignoredApplications)
    }

    private static func loadIgnoredApplications(from defaults: UserDefaults) -> [ClipboardSourceApplication] {
        guard let data = defaults.data(forKey: DefaultsKey.ignoredApplications),
              let applications = try? JSONDecoder().decode([ClipboardSourceApplication].self, from: data) else {
            return []
        }

        return applications.sorted {
            $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending
        }
    }

    private static let pauseTimeFormatter: DateFormatter = {
        let formatter = DateFormatter()
        formatter.timeStyle = .short
        formatter.dateStyle = .none
        return formatter
    }()

    private func pruneHistory(now: Date? = nil) {
        let now = now ?? clock.now()
        removeExpiredUnpinnedItems(now: now)
        trimToLimit()
    }

    private func pruneHistoryAndPersistIfNeeded(now: Date? = nil) {
        guard !isTransferBusy else { return }
        let now = now ?? clock.now()
        let oldItems = items

        pruneHistory(now: now)

        if items != oldItems {
            persist()
        }
    }

    private func removeExpiredUnpinnedItems(now: Date) {
        guard let expirationInterval = retentionPolicy.expirationInterval else {
            return
        }

        let cutoffDate = now.addingTimeInterval(-expirationInterval)
        items.removeAll { item in
            !item.isPinned && item.lastCopiedAt < cutoffDate
        }
    }

    private func trimToLimit() {
        var unpinnedCount = 0
        items.removeAll { item in
            if item.isPinned {
                return false
            }
            unpinnedCount += 1
            return unpinnedCount > historyLimit
        }
    }

    private func persist() {
        persistWorkItem?.cancel()
        let generation = persistenceGeneration.advance()
        let snapshot = items
        let storageRef = storage
        let persistenceGeneration = persistenceGeneration
        let workItem = DispatchWorkItem { [weak self] in
            guard persistenceGeneration.isCurrent(generation) else {
                return
            }
            do {
                let persistedItems = try storageRef.saveValidated(snapshot)
                DispatchQueue.main.async {
                    guard persistenceGeneration.isCurrent(generation) else {
                        return
                    }
                    self?.applyPersistedImageReferences(persistedItems)
                    self?.storageErrorMessage = nil
                }
            } catch {
                DispatchQueue.main.async {
                    self?.storageErrorMessage = error.localizedDescription
                }
            }
        }
        persistWorkItem = workItem
        persistenceQueue.asyncAfter(deadline: .now() + 0.15, execute: workItem)
    }

    @discardableResult
    func flushPendingPersist() -> Bool {
        invalidatePendingPersist()
        let snapshot = items
        do {
            let persistedItems = try persistenceQueue.sync {
                try storage.saveValidated(snapshot)
            }
            applyPersistedImageReferences(persistedItems)
            storageErrorMessage = nil
            return true
        } catch {
            storageErrorMessage = error.localizedDescription
            return false
        }
    }

    private func invalidatePendingPersist() {
        persistWorkItem?.cancel()
        persistWorkItem = nil
        _ = persistenceGeneration.advance()
    }

    private func applyPersistedImageReferences(_ persistedItems: [ClipboardItem]) {
        let persistedByID = Dictionary(uniqueKeysWithValues: persistedItems.map { ($0.id, $0) })
        var updatedItems = items
        var didChange = false

        for index in updatedItems.indices {
            guard let currentImage = updatedItems[index].image,
                  let persistedImage = persistedByID[updatedItems[index].id]?.image,
                  currentImage.contentHash == persistedImage.contentHash,
                  currentImage != persistedImage else {
                continue
            }

            updatedItems[index].image = persistedImage
            didChange = true
        }

        if didChange {
            items = updatedItems
        }
    }

    func dismissStorageError() {
        storageErrorMessage = nil
    }

    func dismissCaptureWarning() {
        captureWarning = nil
    }

    private func mergedItems(existing: [ClipboardItem], imported: [ClipboardItem]) -> [ClipboardItem] {
        var result = existing

        for importedItem in imported {
            let matchingIndex = result.firstIndex { existingItem in
                if existingItem.id == importedItem.id { return true }
                guard existingItem.contentKind == importedItem.contentKind else { return false }
                switch importedItem.contentKind {
                case .text:
                    return existingItem.text == importedItem.text
                case .image:
                    guard let importedHash = importedItem.image?.contentHash else { return false }
                    return existingItem.image?.contentHash == importedHash
                }
            }

            if let matchingIndex {
                var preferred = result[matchingIndex].lastCopiedAt >= importedItem.lastCopiedAt
                    ? result[matchingIndex]
                    : importedItem
                preferred.isPinned = result[matchingIndex].isPinned || importedItem.isPinned
                preferred.copyCount = max(result[matchingIndex].copyCount, importedItem.copyCount)
                result[matchingIndex] = preferred
            } else {
                result.append(importedItem)
            }
        }

        return result.sorted { $0.lastCopiedAt > $1.lastCopiedAt }
    }

    private func importCandidate(
        beforePruning: [ClipboardItem],
        sourceItemCount: Int,
        addedCount: Int,
        strategy: ClipboardImportStrategy,
        now: Date
    ) -> (items: [ClipboardItem], projection: ClipboardImportProjection) {
        let afterExpiration = itemsAfterExpiration(beforePruning, now: now)
        let finalItems = itemsAfterLimit(afterExpiration)
        return (
            finalItems,
            ClipboardImportProjection(
                strategy: strategy,
                sourceItemCount: sourceItemCount,
                addedCount: addedCount,
                deduplicatedCount: strategy == .merge
                    ? max(sourceItemCount - addedCount, 0)
                    : 0,
                expiredCount: beforePruning.count - afterExpiration.count,
                overLimitCount: afterExpiration.count - finalItems.count,
                retainedPinnedCount: finalItems.filter(\.isPinned).count,
                finalCount: finalItems.count
            )
        )
    }

    private func commitImportOnPersistenceQueue(
        currentItems: [ClipboardItem],
        candidateItems: [ClipboardItem]
    ) async throws -> ClipboardImportCommit {
        let cancellationState = ImportCancellationState()
        let storage = storage

        return try await withTaskCancellationHandler {
            try await withCheckedThrowingContinuation { continuation in
                persistenceQueue.async {
                    do {
                        try cancellationState.checkCancellation()
                        try storage.saveValidated(currentItems)
                        let backupURL = try storage.backup(
                            currentItems,
                            reason: "pre-import"
                        )
                        try cancellationState.checkCancellation()
                        try storage.saveValidated(candidateItems)
                        let loadedItems = try storage.loadResult().get().sorted {
                            $0.lastCopiedAt > $1.lastCopiedAt
                        }
                        continuation.resume(
                            returning: ClipboardImportCommit(
                                backupURL: backupURL,
                                items: loadedItems
                            )
                        )
                    } catch {
                        continuation.resume(throwing: error)
                    }
                }
            }
        } onCancel: {
            cancellationState.cancel()
        }
    }

    private func prunedItems(_ candidateItems: [ClipboardItem], now: Date? = nil) -> [ClipboardItem] {
        let now = now ?? clock.now()
        return itemsAfterLimit(itemsAfterExpiration(candidateItems, now: now))
    }

    private func itemsAfterExpiration(
        _ candidateItems: [ClipboardItem],
        now: Date
    ) -> [ClipboardItem] {
        var result = candidateItems.sorted { $0.lastCopiedAt > $1.lastCopiedAt }
        if let expirationInterval = retentionPolicy.expirationInterval {
            let cutoffDate = now.addingTimeInterval(-expirationInterval)
            result.removeAll { !$0.isPinned && $0.lastCopiedAt < cutoffDate }
        }
        return result
    }

    private func itemsAfterLimit(_ candidateItems: [ClipboardItem]) -> [ClipboardItem] {
        var result = candidateItems
        var unpinnedCount = 0
        result.removeAll { item in
            guard !item.isPinned else { return false }
            unpinnedCount += 1
            return unpinnedCount > historyLimit
        }
        return result
    }

    private func clearCopiedIndicator(after id: ClipboardItem.ID) {
        clearCopiedIndicatorTask?.cancel()
        clearCopiedIndicatorTask = Task { @MainActor [weak self] in
            guard let self else { return }
            try? await self.clock.sleep(1_200_000_000)
            guard !Task.isCancelled else { return }
            guard self.lastCopiedID == id else { return }
            self.lastCopiedID = nil
        }
    }
}
