import AppKit
import Combine
import Foundation

enum ClipboardImportStrategy: Sendable, Equatable {
    case merge
    case replace
}

struct ClipboardStoreClock: Sendable {
    var now: @Sendable () -> Date
    var sleep: @Sendable (UInt64) async throws -> Void

    static let live = ClipboardStoreClock(
        now: { Date() },
        sleep: { try await Task.sleep(nanoseconds: $0) }
    )
}

@MainActor
final class ClipboardStore: ObservableObject {
    private enum DefaultsKey {
        static let historyLimit = "historyLimit"
        static let retentionPolicy = "retentionPolicy"
        static let keepPinnedOnClear = "keepPinnedOnClear"
        static let clearUnpinnedOnQuit = "clearUnpinnedOnQuit"
        static let monitoringEnabled = "monitoringEnabled"
        static let monitoringPausedUntil = "monitoringPausedUntil"
        static let directPasteEnabled = "directPasteEnabled"
    }

    private static let defaultHistoryLimit = 50
    private static let pollInterval: TimeInterval = 0.5
    private static let pruneInterval: TimeInterval = 15 * 60
    private static let backupCleanupErrorMessage =
        "Clipboard backups could not be deleted. Check the Data section in Settings."
    private static let ignoredPasteboardTypes: Set<NSPasteboard.PasteboardType> = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType")
    ]

    private var historyPolicy: ClipboardHistoryPolicy {
        ClipboardHistoryPolicy(
            unpinnedLimit: historyLimit,
            retentionPolicy: retentionPolicy
        )
    }

    @Published private(set) var items: [ClipboardItem]
    @Published private(set) var historyLimit: Int
    @Published private(set) var retentionPolicy: ClipboardRetentionPolicy
    @Published var keepPinnedOnClear: Bool {
        didSet {
            defaults.set(keepPinnedOnClear, forKey: DefaultsKey.keepPinnedOnClear)
        }
    }
    @Published var clearUnpinnedOnQuit: Bool {
        didSet {
            defaults.set(clearUnpinnedOnQuit, forKey: DefaultsKey.clearUnpinnedOnQuit)
        }
    }
    @Published var directPasteEnabled: Bool {
        didSet {
            defaults.set(directPasteEnabled, forKey: DefaultsKey.directPasteEnabled)
        }
    }
    @Published private(set) var isMonitoringEnabled: Bool {
        didSet {
            defaults.set(isMonitoringEnabled, forKey: DefaultsKey.monitoringEnabled)
            if isMonitoringEnabled {
                lastPasteboardChangeCount = pasteboard.changeCount
                startMonitoring()
            } else {
                stopMonitoring()
            }
        }
    }
    @Published private(set) var monitoringPausedUntil: Date?
    @Published private(set) var ignoredApplications: [ClipboardSourceApplication]
    @Published private(set) var lastCopiedID: ClipboardItem.ID?
    @Published private(set) var storageErrorMessage: String?
    @Published private(set) var captureWarning: String?
    @Published private(set) var pasteboardWriteWarning: String?
    @Published private(set) var backupInventory: ClipboardBackupInventory
    private let pasteboard: any ClipboardStorePasteboard
    private let storage: any ClipboardStoreRepository
    private let defaults: UserDefaults
    private let ignoredApplicationStore: ClipboardIgnoredApplicationStore
    private let sourceApplicationProvider: () -> ClipboardSourceApplication?
    private let usesWorkspaceSourceTracking: Bool
    private var lastPasteboardChangeCount: Int
    private var lastActiveApplication: ClipboardSourceApplication?
    private var persistenceBlockedByLoadFailure: Bool
    private var persistenceLoadFailureMessage: String?
    nonisolated(unsafe) private var workspaceActivationObserver: NotificationObserverToken?
    private var clearCopiedIndicatorTask: Task<Void, Never>?
    private let persistenceCoordinator: ClipboardPersistenceCoordinator
    private let imageCaptureQueue: ClipboardImageCaptureQueue
    private let pasteboardWriter: any ClipboardPasteboardWriting
    private let dragProviderFactory: ClipboardDragProviderFactory
    private let transferCoordinator: ClipboardStoreTransferCoordinator
    private let clock: ClipboardStoreClock
    private let monitoringSchedule: ClipboardMonitoringSchedule
    private var thumbnailCache = ClipboardThumbnailCache()
    private let thumbnailLoader: @Sendable (ClipboardItem) -> ClipboardThumbnailResult?
    private var transferObservation: AnyCancellable? = nil
    private var exportLimitWarningMessage: String?

    var isTransferBusy: Bool { transferCoordinator.isBusy }
    var transferProgressText: String? { transferCoordinator.progressText }

    var storageLocation: URL {
        storage.fileURL
    }

    var backupLocation: URL {
        storage.fileURL.deletingLastPathComponent()
    }

    func cachedThumbnailData(for item: ClipboardItem) -> Data? {
        switch thumbnailCache.lookup(for: item, now: clock.now()) {
        case let .data(data):
            return data
        case .unavailable:
            return nil
        case let .load(load):
            let thumbnailLoader = thumbnailLoader
            let expectedContentHash = item.image?.contentHash
            let expectedFileName = item.image?.fileName
            Task { @MainActor [weak self] in
                let result = await Task.detached(priority: .utility) {
                    thumbnailLoader(item)
                }.value
                guard let self else { return }
                guard let result,
                      let itemIndex = self.items.firstIndex(where: { $0.id == item.id }),
                      self.items[itemIndex].image?.contentHash == expectedContentHash,
                      self.items[itemIndex].image?.fileName == expectedFileName else {
                    self.thumbnailCache.finishLoading(
                        id: item.id,
                        load: load,
                        data: nil,
                        now: self.clock.now()
                    )
                    if result != nil {
                        self.persist()
                    }
                    return
                }
                if self.items[itemIndex].image?.thumbnailFileName != result.fileName {
                    self.items[itemIndex].image?.thumbnailFileName = result.fileName
                    self.items[itemIndex].image?.thumbnailData = nil
                    self.persist()
                }
                self.thumbnailCache.finishLoading(
                    id: item.id,
                    load: load,
                    data: result.data,
                    now: self.clock.now()
                )
                self.objectWillChange.send()
            }
        }
        return nil
    }

    var historySummaryText: String {
        let unpinnedCount = items.filter { !$0.isPinned }.count
        let pinnedCount = items.count - unpinnedCount

        if pinnedCount > 0 {
            return "\(unpinnedCount)/\(historyLimit) unpinned + \(pinnedCount) pinned"
        }

        return "\(unpinnedCount)/\(historyLimit) unpinned"
    }

    var monitoringStatusText: String {
        ClipboardMonitoringPreferences.statusText(
            isEnabled: isMonitoringEnabled,
            pausedUntil: monitoringPausedUntil,
            now: clock.now()
        )
    }

    init(
        pasteboard: any ClipboardStorePasteboard = NSPasteboard.general,
        storage: any ClipboardStoreRepository = ClipboardStorage(),
        defaults: UserDefaults = .standard,
        sourceApplicationProvider: (() -> ClipboardSourceApplication?)? = nil,
        imageProcessor: any ClipboardImageProcessing = ClipboardImageProcessingService(),
        pasteboardWriter: (any ClipboardPasteboardWriting)? = nil,
        thumbnailLoader: (@Sendable (ClipboardItem) -> ClipboardThumbnailResult?)? = nil,
        clock: ClipboardStoreClock = .live
    ) {
        let loadResult = storage.loadResult()
        let ignoredApplicationStore = ClipboardIgnoredApplicationStore(defaults: defaults)
        ClipboardDefaultExclusionsSeeder.seedIfNeeded(
            defaults: defaults,
            store: ignoredApplicationStore
        )
        self.pasteboard = pasteboard
        self.storage = storage
        self.defaults = defaults
        self.ignoredApplicationStore = ignoredApplicationStore
        self.imageCaptureQueue = ClipboardImageCaptureQueue(processor: imageProcessor)
        self.pasteboardWriter = pasteboardWriter ?? SystemClipboardPasteboardWriter(
            pasteboard: pasteboard
        )
        self.dragProviderFactory = ClipboardDragProviderFactory(imageReader: storage)
        let persistenceCoordinator = ClipboardPersistenceCoordinator(storage: storage)
        self.persistenceCoordinator = persistenceCoordinator
        self.transferCoordinator = ClipboardStoreTransferCoordinator(
            transferService: ClipboardTransferService(storage: storage),
            persistenceCoordinator: persistenceCoordinator
        )
        self.clock = clock
        self.monitoringSchedule = ClipboardMonitoringSchedule(clock: clock)
        self.thumbnailLoader = thumbnailLoader ?? { storage.thumbnailDataRepairingIfNeeded(for: $0) }
        self.backupInventory = (try? storage.backupInventory()) ?? .empty
        let usesSystemPasteboard = pasteboard is NSPasteboard
        self.sourceApplicationProvider = sourceApplicationProvider
            ?? (usesSystemPasteboard ? ClipboardSourceApplication.frontmost : { nil })
        self.usesWorkspaceSourceTracking = sourceApplicationProvider == nil && usesSystemPasteboard
        self.lastActiveApplication = usesWorkspaceSourceTracking
            ? ClipboardSourceApplication.frontmost()
            : nil
        switch loadResult {
        case let .success(loadedItems):
            self.items = loadedItems.sorted { $0.lastCopiedAt > $1.lastCopiedAt }
            self.storageErrorMessage = nil
            self.persistenceBlockedByLoadFailure = false
            self.persistenceLoadFailureMessage = nil
        case let .failure(error):
            self.items = []
            self.storageErrorMessage = error.localizedDescription
            self.persistenceBlockedByLoadFailure = true
            self.persistenceLoadFailureMessage = error.localizedDescription
        }
        self.captureWarning = nil
        let storedHistoryLimit = defaults.object(forKey: DefaultsKey.historyLimit) as? Int
            ?? Self.defaultHistoryLimit
        let normalizedHistoryLimit = min(max(storedHistoryLimit, 10), 200)
        self.historyLimit = normalizedHistoryLimit
        if storedHistoryLimit != normalizedHistoryLimit {
            defaults.set(normalizedHistoryLimit, forKey: DefaultsKey.historyLimit)
        }
        self.retentionPolicy = defaults.string(forKey: DefaultsKey.retentionPolicy)
            .flatMap(ClipboardRetentionPolicy.init(rawValue:))
            ?? .sevenDays
        self.keepPinnedOnClear = defaults.object(forKey: DefaultsKey.keepPinnedOnClear) as? Bool
            ?? true
        self.clearUnpinnedOnQuit = defaults.object(forKey: DefaultsKey.clearUnpinnedOnQuit) as? Bool
            ?? false
        self.directPasteEnabled = defaults.object(forKey: DefaultsKey.directPasteEnabled) as? Bool
            ?? false
        self.ignoredApplications = ignoredApplicationStore.load()
        let monitoringState = ClipboardMonitoringPreferences.initialState(
            defaults: defaults,
            now: clock.now()
        )
        self.monitoringPausedUntil = monitoringState.pausedUntil
        self.isMonitoringEnabled = monitoringState.isEnabled
        self.lastPasteboardChangeCount = pasteboard.changeCount
        self.transferObservation = transferCoordinator.objectWillChange.sink { [weak self] in
            self?.objectWillChange.send()
        }

        let oldItems = items
        pruneHistory()
        if items != oldItems {
            persist()
        }
        if isMonitoringEnabled {
            startMonitoring()
        }
        scheduleMonitoringResumeIfNeeded()
        startPeriodicPruning()
        installWorkspaceSourceTrackingIfNeeded()
    }

    deinit {
        clearCopiedIndicatorTask?.cancel()
        persistenceCoordinator.invalidateScheduledSave()
        if let workspaceActivationObserver {
            NSWorkspace.shared.notificationCenter.removeObserver(workspaceActivationObserver.value)
        }
    }

    func visibleItems(matching query: String, filter: ClipboardContentFilter = .all) -> [ClipboardItem] {
        let filteredItems = items.filter { filter.matches($0) }
        let searchQuery = ClipboardSearchQuery(query)
        return filteredItems.filter(searchQuery.matches)
    }

    func setHistoryLimit(_ limit: Int) {
        guard !isTransferBusy else { return }
        let normalizedLimit = min(max(limit, 10), 200)
        guard normalizedLimit != historyLimit else { return }
        historyLimit = normalizedLimit
        defaults.set(historyLimit, forKey: DefaultsKey.historyLimit)
        pruneHistory()
        persist()
    }

    func setRetentionPolicy(_ policy: ClipboardRetentionPolicy) {
        guard !isTransferBusy, policy != retentionPolicy else { return }
        retentionPolicy = policy
        defaults.set(retentionPolicy.rawValue, forKey: DefaultsKey.retentionPolicy)
        pruneHistory()
        persist()
    }

    func prospectiveDeletionCount(
        historyLimit proposedHistoryLimit: Int? = nil,
        retentionPolicy proposedRetentionPolicy: ClipboardRetentionPolicy? = nil,
        now: Date? = nil
    ) -> Int {
        let proposedPolicy = ClipboardHistoryPolicy(
            unpinnedLimit: min(max(proposedHistoryLimit ?? historyLimit, 10), 200),
            retentionPolicy: proposedRetentionPolicy ?? retentionPolicy
        )
        let result = ClipboardHistoryRules.applyingPolicy(
            to: items,
            policy: proposedPolicy,
            now: now ?? clock.now()
        )
        return result.expiredCount + result.overLimitCount
    }

    func setMonitoringEnabled(_ enabled: Bool) {
        clearMonitoringPause()
        if !enabled {
            invalidatePendingImageCaptures()
        }
        isMonitoringEnabled = enabled
    }

    func pauseMonitoring(for duration: ClipboardPauseDuration) {
        let until = duration.resumeDate(from: clock.now())
        monitoringPausedUntil = until
        defaults.set(until, forKey: DefaultsKey.monitoringPausedUntil)
        invalidatePendingImageCaptures()
        isMonitoringEnabled = false
        scheduleMonitoringResumeIfNeeded()
    }

    func addIgnoredApplication(_ application: ClipboardSourceApplication) {
        if let ownBundleIdentifier = Bundle.main.bundleIdentifier,
           application.bundleIdentifier == ownBundleIdentifier {
            return
        }

        guard !ignoredApplications.contains(where: { $0.bundleIdentifier == application.bundleIdentifier }) else {
            return
        }

        ignoredApplications.append(application)
        ignoredApplications.sort { $0.name.localizedCaseInsensitiveCompare($1.name) == .orderedAscending }
        persistIgnoredApplications()
    }

    func removeIgnoredApplication(_ application: ClipboardSourceApplication) {
        ignoredApplications.removeAll { $0.bundleIdentifier == application.bundleIdentifier }
        persistIgnoredApplications()
    }

    func isApplicationIgnored(_ application: ClipboardSourceApplication?) -> Bool {
        guard let application else {
            return false
        }

        return ignoredApplications.contains { $0.bundleIdentifier == application.bundleIdentifier }
    }

    func exportHistoryAsync(to url: URL) async throws {
        defer {
            discardPasteboardChangesObservedDuringTransfer()
        }
        try await transferCoordinator.export(items, to: url)
    }

    func prepareImport(from url: URL) async throws -> ClipboardImportArtifact {
        defer {
            discardPasteboardChangesObservedDuringTransfer()
        }
        return try await transferCoordinator.prepareImport(from: url)
    }

    func prepareImport(
        data: Data,
        sourceFileName: String
    ) async throws -> ClipboardImportArtifact {
        defer {
            discardPasteboardChangesObservedDuringTransfer()
        }
        return try await transferCoordinator.prepareImport(
            data: data,
            sourceFileName: sourceFileName
        )
    }

    func dragItemProvider(for item: ClipboardItem) -> NSItemProvider {
        dragProviderFactory.provider(for: item)
    }

    func importProjection(
        for artifact: ClipboardImportArtifact,
        strategy: ClipboardImportStrategy,
        now: Date? = nil
    ) -> ClipboardImportProjection {
        importPlan(for: artifact, now: now).projection(for: strategy)
    }

    func importPlan(
        for artifact: ClipboardImportArtifact,
        now: Date? = nil
    ) -> ClipboardImportPlan {
        ClipboardImportPlanner.plan(
            artifact: artifact,
            currentItems: items,
            policy: historyPolicy,
            retentionPolicy: retentionPolicy,
            now: now ?? clock.now()
        )
    }

    @discardableResult
    func importHistory(
        artifact: ClipboardImportArtifact,
        strategy: ClipboardImportStrategy
    ) async throws -> ClipboardImportCommit {
        try await importHistory(
            plan: importPlan(for: artifact),
            strategy: strategy
        )
    }

    @discardableResult
    func importHistory(
        plan: ClipboardImportPlan,
        strategy: ClipboardImportStrategy
    ) async throws -> ClipboardImportCommit {
        guard items == plan.currentItems,
              historyLimit == plan.historyLimit,
              retentionPolicy == plan.retentionPolicy else {
            throw ClipboardStorageError.importPlanExpired
        }

        invalidatePendingImageCaptures()
        invalidatePendingPersist()
        stopMonitoring()
        defer {
            discardPasteboardChangesObservedDuringTransfer()
            if isMonitoringEnabled {
                startMonitoring()
            }
        }

        defer { refreshBackupInventory() }
        let commit = try await transferCoordinator.commitImport(
            plan: plan,
            strategy: strategy
        )
        items = commit.items
        thumbnailCache = ClipboardThumbnailCache()
        clearExportLimitWarningIfResolved()
        persistenceBlockedByLoadFailure = false
        persistenceLoadFailureMessage = nil
        storageErrorMessage = nil
        return commit
    }

    @discardableResult
    func copy(_ item: ClipboardItem) -> Bool {
        copy(item, includingRichText: true)
    }

    @discardableResult
    func copyWithoutFormatting(_ item: ClipboardItem) -> Bool {
        guard item.contentKind == .text else { return false }
        return copy(item, includingRichText: false)
    }

    @discardableResult
    private func copy(
        _ item: ClipboardItem,
        includingRichText: Bool
    ) -> Bool {
        guard !isTransferBusy else {
            return false
        }
        guard let index = items.firstIndex(where: { $0.id == item.id }) else {
            return false
        }

        let imageData: Data?
        if item.contentKind == .image {
            guard let storedImageData = storage.imageData(for: item) else {
                storageErrorMessage = "This image is missing from local storage and was not copied."
                return false
            }
            imageData = storedImageData
        } else {
            imageData = nil
        }

        let writeResult = writeToPasteboard(
            item,
            imageData: imageData,
            includingRichText: includingRichText
        )
        guard writeResult.wroteRequiredRepresentations else {
            storageErrorMessage = "The clip could not be written to the system clipboard."
            return false
        }
        if case let .degraded(optionalTypes) = writeResult {
            pasteboardWriteWarning = "The clip was copied without optional formats: \(optionalTypes.joined(separator: ", "))."
        } else {
            pasteboardWriteWarning = nil
        }
        storageErrorMessage = nil

        var updated = items.remove(at: index)
        updated.lastCopiedAt = clock.now()
        updated.copyCount += 1
        items.insert(updated, at: 0)

        lastPasteboardChangeCount = pasteboard.changeCount
        lastCopiedID = updated.id

        pruneHistory()
        persist()
        clearCopiedIndicator(after: updated.id)
        return true
    }

    func copyWithTransformation(_ item: ClipboardItem, transformation: TextTransformation) {
        guard !isTransferBusy else { return }
        let transformedText = transformation.applied(to: item.text)
        guard !transformedText.isEmpty else {
            return
        }
        guard transformedText.count <= ClipboardStorage.maximumImportedTextCharacters else {
            captureWarning = "A text clip was skipped because it exceeds 20,000 characters."
            return
        }

        let result = pasteboardWriter.write(
            ClipboardPasteboardWriteRequest(
                required: [
                    ClipboardPasteboardRepresentation(.string, value: .string(transformedText))
                ],
                optional: []
            )
        )
        guard result.wroteRequiredRepresentations else {
            storageErrorMessage = "The transformed clip could not be written to the system clipboard."
            return
        }
        storageErrorMessage = nil
        lastPasteboardChangeCount = pasteboard.changeCount

        if let existingIndex = items.firstIndex(where: {
            $0.contentKind == .text && $0.text == transformedText
        }) {
            var existing = items.remove(at: existingIndex)
            existing.lastCopiedAt = clock.now()
            existing.copyCount += 1
            existing.sourceApplication = item.sourceApplication ?? existing.sourceApplication
            items.insert(existing, at: 0)
        } else {
            items.insert(
                ClipboardItem(text: transformedText, sourceApplication: item.sourceApplication),
                at: 0
            )
        }

        pruneHistory()
        persist()

        if let recordedItem = items.first, recordedItem.text == transformedText {
            lastCopiedID = recordedItem.id
            clearCopiedIndicator(after: recordedItem.id)
        }
    }

    func togglePin(_ item: ClipboardItem) {
        guard !isTransferBusy else { return }
        guard let index = items.firstIndex(where: { $0.id == item.id }) else {
            return
        }

        setPinned(!items[index].isPinned, ids: [item.id])
    }

    func setPinned(_ isPinned: Bool, ids: Set<ClipboardItem.ID>) {
        guard !isTransferBusy else { return }
        let matchingIndices = items.indices.filter { ids.contains(items[$0].id) }
        guard matchingIndices.contains(where: { items[$0].isPinned != isPinned }) else {
            return
        }
        for index in matchingIndices {
            items[index].isPinned = isPinned
        }
        pruneHistory()
        persist()
        if isPinned, items.count > ClipboardStorage.maximumImportedItems {
            let warning = "History cannot be exported: "
                + ClipboardTransferCodec.itemLimitExceededReason(itemCount: items.count)
            exportLimitWarningMessage = warning
            captureWarning = warning
        }
    }

    func unpinAll() {
        guard !isTransferBusy, items.contains(where: \.isPinned) else { return }
        for index in items.indices {
            items[index].isPinned = false
        }
        pruneHistory()
        persist()
    }

    func prospectiveUnpinAllDeletionCount(now: Date? = nil) -> Int {
        let unpinnedItems = items.map { item in
            var item = item
            item.isPinned = false
            return item
        }
        let result = ClipboardHistoryRules.applyingPolicy(
            to: unpinnedItems,
            policy: historyPolicy,
            now: now ?? clock.now()
        )
        return result.expiredCount + result.overLimitCount
    }

    @discardableResult
    func delete(_ item: ClipboardItem) async -> Bool {
        await delete(ids: [item.id])
    }

    @discardableResult
    func delete(ids: Set<ClipboardItem.ID>) async -> Bool {
        guard !isTransferBusy else { return false }
        let removedIDs = Set(items.filter { ids.contains($0.id) }.map(\.id))
        guard !removedIDs.isEmpty else { return false }
        items.removeAll { removedIDs.contains($0.id) }
        thumbnailCache.invalidate(ids: removedIDs)
        clearExportLimitWarningIfResolved()
        return await flushPendingPersist()
    }

    @discardableResult
    func clearHistory() async -> Bool {
        guard !isTransferBusy else { return false }
        invalidatePendingImageCaptures()
        let previousIDs = Set(items.map(\.id))
        if keepPinnedOnClear {
            items.removeAll { !$0.isPinned }
        } else {
            items.removeAll()
        }

        thumbnailCache.invalidate(ids: previousIDs.subtracting(items.map(\.id)))
        clearExportLimitWarningIfResolved()
        guard await flushPendingPersist() else {
            return false
        }
        return await purgeBackupsReportingFailureAsync()
    }

    private func startMonitoring() {
        guard isMonitoringEnabled else { return }
        monitoringSchedule.startPolling(interval: Self.pollInterval) { [weak self] in
            self?.pollPasteboardForChanges()
        }
    }

    private func stopMonitoring() {
        monitoringSchedule.stopPolling()
    }

    private func discardPasteboardChangesObservedDuringTransfer() {
        lastPasteboardChangeCount = pasteboard.changeCount
    }

    private func startPeriodicPruning() {
        monitoringSchedule.startPruning(interval: Self.pruneInterval) { [weak self] in
            self?.pruneHistoryAndPersistIfNeeded()
        }
    }

    func pollPasteboardForChanges(sourceApplicationOverride: ClipboardSourceApplication? = nil) {
        guard isMonitoringEnabled, !isTransferBusy else {
            return
        }
        let currentChangeCount = pasteboard.changeCount

        guard currentChangeCount != lastPasteboardChangeCount else {
            return
        }

        lastPasteboardChangeCount = currentChangeCount

        guard !shouldIgnoreCurrentPasteboard() else {
            return
        }

        let sourceApplication = sourceApplicationOverride
            ?? (usesWorkspaceSourceTracking ? lastActiveApplication : sourceApplicationProvider())
        guard !isApplicationIgnored(sourceApplication) else {
            return
        }

        let capturedText = ClipboardCaptureReader.text(from: pasteboard)
        if let warning = capturedText.warning {
            captureWarning = warning
        }

        if let candidate = ClipboardCaptureReader.image(from: pasteboard) {
            let capturedAt = clock.now()
            processImageCandidate(
                candidate,
                associatedText: capturedText.snapshot,
                associatedWarning: capturedText.warning,
                sourceApplication: sourceApplication,
                capturedAt: capturedAt
            )
            return
        }

        guard let textSnapshot = capturedText.snapshot else {
            return
        }

        record(
            textSnapshot.text,
            rtfData: textSnapshot.rtfData,
            htmlData: textSnapshot.htmlData,
            sourceApplication: sourceApplication,
            capturedAt: clock.now()
        )
        captureWarning = capturedText.warning
    }

    private func shouldIgnoreCurrentPasteboard() -> Bool {
        guard let types = pasteboard.types else {
            return false
        }

        return types.contains { Self.ignoredPasteboardTypes.contains($0) }
    }

    private func processImageCandidate(
        _ candidate: ClipboardImageCandidate,
        associatedText: CapturedTextSnapshot?,
        associatedWarning: String?,
        sourceApplication: ClipboardSourceApplication?,
        capturedAt: Date
    ) {
        imageCaptureQueue.enqueue(
            ClipboardImageCaptureRequest(
                candidate: candidate,
                associatedText: associatedText,
                associatedWarning: associatedWarning,
                sourceApplication: sourceApplication,
                capturedAt: capturedAt
            )
        ) { [weak self] outcome in
            guard let self else { return }
            switch outcome {
            case let .processed(image, request):
                record(
                    image,
                    associatedText: request.associatedText?.text,
                    sourceApplication: request.sourceApplication,
                    capturedAt: request.capturedAt
                )
                captureWarning = request.associatedWarning
            case let .failed(message, request):
                captureWarning = request.candidate.isSoleFileURLSource
                    ? request.associatedWarning
                    : message
                if let associatedText = request.associatedText {
                    record(
                        associatedText.text,
                        rtfData: associatedText.rtfData,
                        htmlData: associatedText.htmlData,
                        sourceApplication: request.sourceApplication,
                        capturedAt: request.capturedAt
                    )
                }
            }
        }
    }

    private func invalidatePendingImageCaptures() {
        imageCaptureQueue.invalidate()
    }

    @discardableResult
    nonisolated static func clearUnpinnedHistoryOnQuitIfNeeded(
        storage: any ClipboardHistoryRepository = ClipboardStorage(),
        defaults: UserDefaults = .standard
    ) -> Bool {
        guard defaults.bool(forKey: DefaultsKey.clearUnpinnedOnQuit) else {
            return true
        }

        do {
            let loadedItems = try storage.loadResult().get()
            let itemsToKeep = itemsAfterQuitCleanup(loadedItems)
            _ = try storage.saveValidated(itemsToKeep)
            try storage.purgeBackups()
            return true
        } catch {
            return false
        }
    }

    @discardableResult
    func clearUnpinnedHistoryOnQuitIfNeeded() -> Bool {
        invalidatePendingImageCaptures()
        guard clearUnpinnedOnQuit else {
            return flushPendingPersistSynchronously()
        }

        let previousItems = items
        items = Self.itemsAfterQuitCleanup(items)
        thumbnailCache = ClipboardThumbnailCache()

        guard flushPendingPersistSynchronously() else {
            items = previousItems
            thumbnailCache = ClipboardThumbnailCache()
            return false
        }
        return purgeBackupsReportingFailure()
    }

    nonisolated private static func itemsAfterQuitCleanup(
        _ items: [ClipboardItem]
    ) -> [ClipboardItem] {
        items.filter(\.isPinned)
    }

    private func record(
        _ text: String,
        rtfData: Data? = nil,
        htmlData: Data? = nil,
        sourceApplication: ClipboardSourceApplication? = nil,
        capturedAt: Date? = nil
    ) {
        let capturedAt = capturedAt ?? clock.now()
        guard text.count <= ClipboardStorage.maximumImportedTextCharacters else {
            captureWarning = "A text clip was skipped because it exceeds 20,000 characters."
            return
        }

        guard text.rangeOfCharacter(from: .whitespacesAndNewlines.inverted) != nil else {
            return
        }

        items = ClipboardHistoryRules.recordingText(
            text,
            rtfData: rtfData,
            htmlData: htmlData,
            sourceApplication: sourceApplication,
            capturedAt: capturedAt,
            in: items
        )

        pruneHistory()
        persist()
    }

    private func record(
        _ image: ClipboardImagePayload,
        associatedText: String? = nil,
        sourceApplication: ClipboardSourceApplication? = nil,
        capturedAt: Date? = nil
    ) {
        let capturedAt = capturedAt ?? clock.now()
        guard let data = image.data, data.count <= ClipboardImageProcessor.maximumEncodedBytes else {
            captureWarning = ClipboardImageProcessingError.encodedDataTooLarge.localizedDescription
            return
        }

        var storedImage = image
        if storedImage.contentHash == nil {
            storedImage.contentHash = ClipboardImageProcessor.contentHash(for: data)
        }

        items = ClipboardHistoryRules.recordingImage(
            storedImage,
            associatedText: associatedText,
            sourceApplication: sourceApplication,
            capturedAt: capturedAt,
            in: items
        )
        pruneHistory()
        persist()
    }

    @discardableResult
    private func writeToPasteboard(
        _ item: ClipboardItem,
        imageData: Data?,
        includingRichText: Bool = true
    ) -> ClipboardPasteboardWriteResult {
        let request: ClipboardPasteboardWriteRequest
        switch item.contentKind {
        case .text:
            var optional: [ClipboardPasteboardRepresentation] = []
            if includingRichText {
                if let rtfData = item.rtfData {
                    optional.append(ClipboardPasteboardRepresentation(.rtf, value: .data(rtfData)))
                }
                if let htmlData = item.htmlData {
                    optional.append(ClipboardPasteboardRepresentation(.html, value: .data(htmlData)))
                }
            }
            request = ClipboardPasteboardWriteRequest(
                required: [
                    ClipboardPasteboardRepresentation(.string, value: .string(item.text))
                ],
                optional: optional
            )
        case .image:
            guard let imageData else {
                return .failure
            }
            var optional: [ClipboardPasteboardRepresentation] = []
            if !item.text.isEmpty {
                optional.append(
                    ClipboardPasteboardRepresentation(.string, value: .string(item.text))
                )
            }
            request = ClipboardPasteboardWriteRequest(
                required: [
                    ClipboardPasteboardRepresentation(.png, value: .data(imageData))
                ],
                optional: optional
            )
        }
        return pasteboardWriter.write(request)
    }

    private func installWorkspaceSourceTrackingIfNeeded() {
        guard usesWorkspaceSourceTracking else { return }
        workspaceActivationObserver = NotificationObserverToken(
            NSWorkspace.shared.notificationCenter.addObserver(
                forName: NSWorkspace.didActivateApplicationNotification,
                object: nil,
                queue: .main
            ) { [weak self] notification in
                guard let runningApplication = notification.userInfo?[NSWorkspace.applicationUserInfoKey]
                        as? NSRunningApplication else { return }
                MainActor.assumeIsolated {
                    guard let self else { return }
                    let previousApplication = self.lastActiveApplication
                    self.pollPasteboardForChanges(sourceApplicationOverride: previousApplication)
                    self.lastActiveApplication = ClipboardSourceApplication(
                        runningApplication: runningApplication
                    )
                }
            }
        )
    }

    private func clearMonitoringPause() {
        monitoringSchedule.cancelResume()
        monitoringPausedUntil = nil
        defaults.removeObject(forKey: DefaultsKey.monitoringPausedUntil)
    }

    private func scheduleMonitoringResumeIfNeeded() {
        monitoringSchedule.cancelResume()

        guard let monitoringPausedUntil else {
            return
        }

        monitoringSchedule.scheduleResume(at: monitoringPausedUntil) { [weak self] in
            guard let self else { return }
            guard let pausedUntil = self.monitoringPausedUntil,
                  pausedUntil <= self.clock.now() else {
                return
            }

            self.clearMonitoringPause()
            self.isMonitoringEnabled = true
        }
    }

    private func persistIgnoredApplications() {
        ignoredApplicationStore.save(ignoredApplications)
    }

    private func pruneHistory(now: Date? = nil) {
        let now = now ?? clock.now()
        let previousIDs = Set(items.map(\.id))
        items = ClipboardHistoryRules.applyingPolicy(
            to: items,
            policy: historyPolicy,
            now: now
        ).items
        thumbnailCache.invalidate(ids: previousIDs.subtracting(items.map(\.id)))
        clearExportLimitWarningIfResolved()
    }

    private func pruneHistoryAndPersistIfNeeded(now: Date? = nil) {
        guard !isTransferBusy else { return }
        let now = now ?? clock.now()
        let oldItems = items

        pruneHistory(now: now)

        if items != oldItems {
            persist()
        }
    }

    private func persist() {
        guard !persistenceBlockedByLoadFailure else {
            storageErrorMessage = persistenceLoadFailureMessage
            return
        }
        let snapshot = items
        persistenceCoordinator.scheduleSave(snapshot) { [weak self] result in
            guard let self else { return }
            switch result {
            case let .success(persistedItems):
                self.applyPersistedImageReferences(persistedItems)
                self.storageErrorMessage = nil
            case let .failure(error):
                self.storageErrorMessage = error.localizedDescription
            }
        }
    }

    @discardableResult
    func flushPendingPersist() async -> Bool {
        invalidatePendingPersist()
        guard !persistenceBlockedByLoadFailure else {
            storageErrorMessage = persistenceLoadFailureMessage
            return false
        }
        let snapshot = items
        do {
            let persistedItems = try await persistenceCoordinator.flush(snapshot)
            applyPersistedImageReferences(persistedItems)
            storageErrorMessage = nil
            return true
        } catch {
            storageErrorMessage = error.localizedDescription
            return false
        }
    }

    @discardableResult
    private func flushPendingPersistSynchronously() -> Bool {
        invalidatePendingPersist()
        guard !persistenceBlockedByLoadFailure else {
            storageErrorMessage = persistenceLoadFailureMessage
            return false
        }
        let snapshot = items
        do {
            let persistedItems = try persistenceCoordinator.flushSynchronously(snapshot)
            applyPersistedImageReferences(persistedItems)
            storageErrorMessage = nil
            return true
        } catch {
            storageErrorMessage = error.localizedDescription
            return false
        }
    }

    private func invalidatePendingPersist() {
        persistenceCoordinator.invalidateScheduledSave()
    }

    private func applyPersistedImageReferences(_ persistedItems: [ClipboardItem]) {
        let persistedByID = Dictionary(uniqueKeysWithValues: persistedItems.map { ($0.id, $0) })
        var updatedItems = items
        var didChange = false

        for index in updatedItems.indices {
            guard let currentImage = updatedItems[index].image,
                  let persistedImage = persistedByID[updatedItems[index].id]?.image,
                  currentImage.contentHash == persistedImage.contentHash,
                  currentImage != persistedImage else {
                continue
            }

            updatedItems[index].image = persistedImage
            didChange = true
        }

        if didChange {
            items = updatedItems
        }
    }

    func dismissStorageError() {
        storageErrorMessage = nil
    }

    func dismissCaptureWarning() {
        captureWarning = nil
    }

    func dismissPasteboardWriteWarning() {
        pasteboardWriteWarning = nil
    }

    func deleteBackups() {
        guard !isTransferBusy else { return }
        purgeBackupsReportingFailure()
    }

    @discardableResult
    private func purgeBackupsReportingFailure() -> Bool {
        do {
            try storage.purgeBackups()
            backupInventory = .empty
            if storageErrorMessage == Self.backupCleanupErrorMessage {
                storageErrorMessage = nil
            }
            return true
        } catch {
            refreshBackupInventory()
            storageErrorMessage = Self.backupCleanupErrorMessage
            return false
        }
    }

    @discardableResult
    private func purgeBackupsReportingFailureAsync() async -> Bool {
        let storage = storage
        let result = await Task.detached(priority: .utility) {
            Result { try storage.purgeBackups() }
        }.value
        switch result {
        case .success:
            backupInventory = .empty
            if storageErrorMessage == Self.backupCleanupErrorMessage {
                storageErrorMessage = nil
            }
            return true
        case .failure:
            let inventory = await Task.detached(priority: .utility) {
                try? storage.backupInventory()
            }.value
            if let inventory {
                backupInventory = inventory
            }
            storageErrorMessage = Self.backupCleanupErrorMessage
            return false
        }
    }

    private func refreshBackupInventory() {
        if let inventory = try? storage.backupInventory() {
            backupInventory = inventory
        }
    }

    private func clearExportLimitWarningIfResolved() {
        guard items.count <= ClipboardStorage.maximumImportedItems,
              let exportLimitWarningMessage else { return }
        if captureWarning == exportLimitWarningMessage {
            captureWarning = nil
        }
        self.exportLimitWarningMessage = nil
    }

    private func clearCopiedIndicator(after id: ClipboardItem.ID) {
        clearCopiedIndicatorTask?.cancel()
        clearCopiedIndicatorTask = Task { @MainActor [weak self] in
            guard let self else { return }
            try? await self.clock.sleep(1_200_000_000)
            guard !Task.isCancelled else { return }
            guard self.lastCopiedID == id else { return }
            self.lastCopiedID = nil
        }
    }
}
